### ISSUE TITLE
Calendario proyecto

### ISSUE THREAD

**Issue by sreitze** [IIC2143-2021-1/Syllabus#1]
Hola, quería saber si tienen las fechas de las entregas parciales del proyecto semestral, o donde puedo encontrarlas. Muchas gracias.

**Comment by meretamal** [comment]
Hola 😁 

Este viernes se debería subir toda la información relacionada con el proyecto, incluyendo enunciado, fechas y ayudantes a cargo.

**Comment by sreitze** [comment]
Ok, muchas gracias!
