### ISSUE TITLE
Como descargar los documentos de relatos de usuario para Entrega 0

### ISSUE THREAD

**Issue by En-clases** [IIC2143-2021-1/Syllabus#100]
Hola, para la entrega debemos incluir: ```Además, en una carpeta llamada relatos deben incluir el/los documentos de relatos de usuario```. Existe una forma de descargar todos los relatos de usuario de trello? He buscado y al parecer solo se puede exportar los archivos con json gratuitamente y no creo que nos estén pidiendo dichos archivos en ese formato. 
Espero me puedan ayudar, gracias.

**Comment by meretamal** [comment]
Hola 😁 

Tienes que subirlos manualmente

**Comment by En-clases** [comment]
Ok! gracias 😄
