### ISSUE TITLE
Error al hacer el deploy en Heroku

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2143-2021-1/Syllabus#101]
Al hacer el deploy me aparece el siguiente error:

error: src refspec master does not match any
error: failed to push some refs to 'https://git.heroku.com/grupo84.git'

Y no puedo hacer el deploy por eso
Gracias.

**Comment by Daniel-SebastianGaete** [comment]
Qué comandos has usado hasta ahora en el proceso de hacer el deploy?

**Comment by ignaciovilla** [comment]
probe esto:
1) $ heroku login
2) $ heroku git:remote -a nombredelproyecto
3) $ git add .
    $ git commit -am "make it better"
    $ git push heroku master

**Comment by Daniel-SebastianGaete** [comment]
Revisa si estás en la rama principal del repositorio ya que al clonar el repositorio de Github en Heroku solamente se clona la rama principal, en este caso es la rama `main` y no `master`. Te recomiendo fusionar todos los avances que no estén en el repositorio a la rama `main` y subir desde ahí la aplicación a Heroku. Quizá necesites usar `git push heroku main` en vez de `git push heroku master`.
