### ISSUE TITLE
Error instalación Heroku CLI en WSL

### ISSUE THREAD

**Issue by tomgrohnert** [IIC2143-2021-1/Syllabus#102]
Hola, tengo un problema con la instalación de Heroku CLI en WSL. Cuando corro el comando de instalación 'sudo snap install --classic heroku' me tira el siguiente error:
'error: cannot communicate with server: Post http://localhost/v2/snaps/heroku: dial unix /run/snapd.socket: connect: no such file or directory'

**Comment by Daniel-SebastianGaete** [comment]
Intenta con el otro comando que indica Heroku: `curl https://cli-assets.heroku.com/install.sh | sh`
Avísame si te funciona o no. Saludos

**Comment by tomgrohnert** [comment]
Me funciono con ese comando. Gracias
