### ISSUE TITLE
Hardcoding en Ruby/Rails

### ISSUE THREAD

**Issue by imant1** [IIC2143-2021-1/Syllabus#103]
Hola! ¿Cuál es la mejor forma de no hacer _harcoding_ en los archivos  `.html.erb`?
Por ejemplo, el nombre de la página se va a utilizar en varios archivos, por lo que quiero ocupar una pura variable que almacene ese string

**Comment by Daniel-SebastianGaete** [comment]
Puedes usar helpers que retornen valores. No sé si es la mejor forma de no hacer _hardcoding_, pero es una buena forma de reutilizar código. Te dejo un link para que lo investigues en más detalle: https://www.rubyguides.com/2020/01/rails-helpers/

**Comment by imant1** [comment]
![image](https://user-images.githubusercontent.com/64439029/115782170-5c573c00-a389-11eb-9956-baf90a68d7e1.png)
Esta forma me funcionó, pero ¿hay alguna forma de definir una variable que contenga ese string y después llamar a la variable en el `.html.erb` ? ¿O tengo que crear un método para cada variable?

**Comment by meretamal** [comment]
Se lo podrías pasar como un parámetro al método del _Helper_
