### ISSUE TITLE
Error RubyonRails: ActionController::UnknownFormat in UsersController#new

### ISSUE THREAD

**Issue by Emiliax16** [IIC2143-2021-1/Syllabus#104]
Hola ! a modo de práctica, estoy intentando hacer un perfil de usuario siguiendo paso a paso la ayudantía 3 (CRUD). He revisado muchísimas veces y está exactamente igual de lo que hace el ayudante, pero siempre me tira un error que al parecer está relacionado con el path. Intenté muchas soluciones de internet y ninguna me funcionó. Cabe destacar que están todos los end, no hay errores de tipeo (por lo que veo) y el controlador se encuentra en plural.
Adjunto pantallazos del error. Ayuda 😭 
![error1](https://user-images.githubusercontent.com/69869381/116114383-4d250680-a687-11eb-80b7-2b7b45936931.jpg)
![error2](https://user-images.githubusercontent.com/69869381/116114402-50b88d80-a687-11eb-9f7e-899b48287647.jpg)
![error3](https://user-images.githubusercontent.com/69869381/116114411-52825100-a687-11eb-9f9f-0c0af0e43128.jpg)
![error4](https://user-images.githubusercontent.com/69869381/116114425-557d4180-a687-11eb-94de-4789374ac4cb.jpg)
![error5](https://user-images.githubusercontent.com/69869381/116114436-57470500-a687-11eb-8aa2-055d225c70cd.jpg)
![error6](https://user-images.githubusercontent.com/69869381/116114444-5910c880-a687-11eb-8858-2186543575bc.jpg)
![error7](https://user-images.githubusercontent.com/69869381/116114451-5ada8c00-a687-11eb-8e1e-7b7d24eff929.jpg)
![error8](https://user-images.githubusercontent.com/69869381/116114461-5ca44f80-a687-11eb-8b09-1ce6df443626.jpg)

**Comment by jmndoza** [comment]
Hola @Emiliax16, tampoco veo algo extraño, pero podrías probar renombrar la carpeta `user` a `users` que esta dentro de `views`

**Comment by Emiliax16** [comment]
Hola!! funcionó altiro con eso, muchísimas gracias ❤️ hay alguna explicación del porqué en mi caso necesitaba estar en plural el view? todos los ejemplos que he visto, nunca ponen plural el view.

**Comment by jmndoza** [comment]
El comportamiento por defecto es ir a la carpeta con el nombre del controlador, en tu caso es Users.  https://guides.rubyonrails.org/layouts_and_rendering.html
