### ISSUE TITLE
Consulta con el password del usuario postgres

### ISSUE THREAD

**Issue by Gustav2000** [IIC2143-2021-1/Syllabus#11]
Hola, tengo una duda ya que me confunde el tema del password. Al entrar en la consola PostgreSQL como usuario postgres, me pide la contraseña de mi user (se cual es la contraseña, pero no entiendo si esto tiene o no que ver con el usuario que se crea después en el paso 7?). Y después al hacer \du dentro de la consola me muestra que solo está creado el usuario postgres.
![image](https://user-images.githubusercontent.com/62355739/112659223-ef589100-8e32-11eb-9d3a-12429c97bf1f.png)

Después nos dice que nos tenemos que crear un usuario con contraseña. Esta contraseña puede ser diferente a la que me pidió antes? y ésta es la que tengo que colocar después en el archivo .env?
![image](https://user-images.githubusercontent.com/62355739/112659629-52e2be80-8e33-11eb-9632-b32781fab4ca.png)

**Comment by catalina-ramirez** [comment]
Hola @Gustav2000 ,
Cuando crees tu usuario y contraseña puedes elegir la contraseña que quieras, y esa que elijas es la que debes colocar en el archivo .env
Muchos saludos!

**Comment by Gustav2000** [comment]
Muchas gracias.
![image](https://user-images.githubusercontent.com/62355739/112675585-1c626f00-8e46-11eb-9b0f-f231ff30cf07.png)
Entonces esa contraseña que me pide ahí no tiene nada que ver con el usuario que me crearé después para Postgres el cual puede llevar otra contraseña?

**Comment by meretamal** [comment]
Claro, esa es la contraseña del usuario de tu sistema. En ubuntu, cuando corres un comando con `sudo`, es común que te la pida

**Comment by Gustav2000** [comment]
Yaa muchas gracias!
