### ISSUE TITLE
Codigo embebido no se muestra en la vista

### ISSUE THREAD

**Issue by imant1** [IIC2143-2021-1/Syllabus#110]
Hola! Estoy creando el CRUD de las publicaciones siguiendo exactamente la guía de [Rails](https://guides.rubyonrails.org/getting_started.html#creating-a-new-article). Sin embargo, no se me está rendereando el código embebido cuando falla la validación del `.save` de una publicación. Se deberían mostrar los errores pero la vista queda igual que antes. 
Decidí probar con un nuevo proyecto de rails volviendo a hacer los pasos de la guía y tampoco me funciona. 
En el new.html.erb tengo algo del estilo:
```
<% p @article.errors.any? %>
<%if @article.errors.any? %>
  <h1>aquí debería ir un error</h1>
  <%= @article.errors.full_messages %>
  <% p @article.errors.full_messages %>
<%else%>
  <p>no hay error</p>
<%end%>
```
Y cuando pongo un titulo y body (los dos atributos de Article) que no cumplen con los  validate que puse, en consola me tira
```
true
["Body is too short (minimum is 10 characters)",....]
```
En teoría se debería mostrar el output de `full_messages` en la vista de la página y el "aquí debería ir un error", pero la vista queda igual que antes y ninguno se muestra. 

En articles_controller.rb tengo exactamente lo que sale en la guía de [rails](https://guides.rubyonrails.org/getting_started.html#creating-a-new-article) en el punto 6.3.2:
```
def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end
```  

Cualquier ayuda se agradece

**Comment by Daniel-SebastianGaete** [comment]
Pregunta, ¿Por qué pones la `p` antes del código Ruby en las líneas 1 y 5 del `html.erb`?

**Comment by imant1** [comment]
Es el p de puts, lo puse para verificar q efectivamente el erros.any? está retornando true y q se estuvieran generando los errores.
Efectivamente en la consola sale true y los errores.
Entonces si se está leyendo el código embebido, pero no se está actualizando la vista

**Comment by imant1** [comment]
@Daniel-SebastianGaete ¿alguna idea porqué pasa esto?

**Comment by imant1** [comment]
Logré resolverlo, faltaba esto en el form
![image](https://user-images.githubusercontent.com/64439029/117172172-8b15df00-ad99-11eb-93b9-e56c533bdb72.png)
