### ISSUE TITLE
Herencia entre modelos

### ISSUE THREAD

**Issue by camigervasoni** [IIC2143-2021-1/Syllabus#112]
Hola queremos hacer un modelo general y tener otros modelos que hereden de este, y no sabemos como crear la herencia. Es necesario crear los modelos que hereden desde la terminal? O manualmente? 
Y como se podría hacer?
Eso, gracias!

**Comment by alericoj10** [comment]
Hola!! Perdón por la respuesta tarde. Si es que aún siguen con la duda, las 2 maneras son posibles (desde terminal y manualmente)

- Manual: Esta es la sintaxis de herencia de modelos 
```
class Child < Parent
end
```

- Desde terminal: `rails generate model Child --parent=Parent`

Éxito con la entrega!
