### ISSUE TITLE
could not connect to server: No such file or directory Is the server running on "/var/run/postgresql/.s.PGSQL.5432"?

### ISSUE THREAD

**Issue by tago470** [IIC2143-2021-1/Syllabus#115]
Cuando intento crear la base de datos con el comando "rails db:create" me arroja el siguiente error:
rails db:create
could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create 'grupo-43_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/home/tago470/.rvm/gems/ruby-2.6.6/gems/pg-1.2.3/lib/pg.rb:58:in `initialize'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/pg-1.2.3/lib/pg.rb:58:in `new'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/pg-1.2.3/lib/pg.rb:58:in `connect'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/connection_handling.rb:90:in `connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:119:in `create'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:313:in `each'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/railties-5.2.5/lib/rails/command.rb:48:in `invoke'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<main>'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/home/tago470/.rvm/gems/ruby-2.6.6/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:6:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace) 

Estuve un par de horas buscando en internet  y no logré resolverlo, por si me pudieran ayudar. Gracias!

**Comment by Crespy98** [comment]
mira la siguiente issue  #17 que le paso lo mismo
