### ISSUE TITLE
Error al correr servidor:  database does not exist

### ISSUE THREAD

**Issue by tcouso** [IIC2143-2021-1/Syllabus#116]
Hola!

Acabo de hacer pull del branch development, donde mi compañero de grupo hizo merge de sus avances, y al intentar correr el servidor está teniendo el siguiente error: 
![Captura de pantalla 2021-05-02 205258](https://user-images.githubusercontent.com/62035756/116833659-77475e80-ab88-11eb-9cdd-70e3031edf47.png)

No estoy muy seguro de qué estaría pasando, ya que , según me parece, si hice pull debiera tener todos los archivos necesarios para correr el servidor localmente, y dudo que la solución esté en crear una base de datos, pues en ese caso tendría inconsistencias con los archivos del resto de mi grupo.

Cualquier ayuda se agradece un montón!

Saludos!

**Comment by Crespy98** [comment]
Hola revisa la issue #84

**Comment by tcouso** [comment]
Ahí funcionó! No había visto la issue, estaré más atento para la próxima.

Muchas gracias!
