### ISSUE TITLE
Ver flujo de branches desde github

### ISSUE THREAD

**Issue by Gustav2000** [IIC2143-2021-1/Syllabus#117]
Hola quería saber, si es posible que se habilite la opción de **Network** dentro de **Insights** para que podamos ir viendo el flujo de las branches desde github de forma más visual.

![image](https://user-images.githubusercontent.com/62355739/116836750-c21ba300-ab95-11eb-8203-cb2bf7c1f980.png)

**Comment by meretamal** [comment]
Hola 😁 , dado el tipo de organización (_Github Free_), no les podemos dar acceso a esa funcionalidad

**Comment by Gustav2000** [comment]
Ohhh :( . Gracias igual!
