### ISSUE TITLE
Foto de perfil con ActiveStorage

### ISSUE THREAD

**Issue by stgo32** [IIC2143-2021-1/Syllabus#118]
Hola, 
Estoy usando active storage para poder tener fotos de perfil en los usuarios. Funciona bien tanto en mi computador como en los de los demás de mis compañeros.
Lamentablemente, tambien tuve que descargar ImageMagick que funciona bien localmente pero mis compañeros deben hacer
`sudo apt install imagemagick`
para que la gema funcione. Lo que me hace preguntarme cómo va a funcionar esto en heroku.

El error puntual es:
`You must have ImageMagick`
Localmente yo tengo la gema pero no se si remotamente funcionará.

**Comment by josemquinta15** [comment]
Hola, no soy ayudante, pero lo que se me ocurre es que tendrías que instalar imagemagick en heroku... aquí hay un link donde se explica como https://elements.heroku.com/buildpacks/duckyteam/heroku-buildpack-imagemagick
Avísame si te sirve, pq probablemente tendré que hacer lo mismo más adelante

**Comment by stgo32** [comment]
Buena gracias!! voy a ver como me va
