### ISSUE TITLE
FATAL: role "root" does not exist

### ISSUE THREAD

**Issue by imant1** [IIC2143-2021-1/Syllabus#12]
Hola! 
Hice todos los pasos de la guía, pero cuando corro `rails s` y me meto al `localhost:3000`  me sale lo siguiente:

![image](https://user-images.githubusercontent.com/64439029/112659016-c33d1000-8e32-11eb-851d-bf4a15da0b91.png)
  

En la ayudantía de hoy día (viernes 26/03) me fijé que en las consolas de los ayudantes y compañeros la línea de comando partía con algo del estilo <nombre_usuario>@<otra_cosa>:~...
Pero en mi línea de comando aparece root@Desktop-5IC...
![image](https://user-images.githubusercontent.com/64439029/112659827-89b8d480-8e33-11eb-9fd6-f067bf9c5157.png)

Puede que esto tenga que ver con el error que me sale.

Se agradece cualquier ayuda!

**Comment by fbpesenti** [comment]
Hola @ignaciomansuy ,

No creo que el problema sea de ubuntu/ linux, me parece que se te creo el nombre de usuario como root 

Primero podrías mandar un screenshot de tu database.yml y de como seteaste el usuario de postgres

Saludos,

**Comment by meretamal** [comment]
Hola Ignacio, otra posible causa que surgió en la ayudantía de hoy, es que no es está leyendo bien el archivo **.env**. Intenta agregando esta línea al final de tu **Gemfile**:

```gem 'dotenv-rails', groups: [:development, :test]```

y luego ejecutando `bundle install`

**Comment by imant1** [comment]
Hola @meretamal, hice lo que pusiste, luego corrí `rails s` y enseguida a localhost:3000 y me tiró este error
![image](https://user-images.githubusercontent.com/64439029/112675141-8af2fd00-8e45-11eb-9b05-73f727c744a7.png)

Hola @fbpesenti, aquí el screenshot del archivo `database.yml`:
![image](https://user-images.githubusercontent.com/64439029/112675573-179dbb00-8e46-11eb-9725-945f6e7fad30.png)

En cuanto a cómo configuré el usuario de postgres, no lo puedo mandar ya que tuve que cerrar la consola y perdí el "historial" de comandos que corrí. Si hay otra forma de revisar lo que me pides te agradecería indicármelo y lo envío lo antes posible.

**Comment by meretamal** [comment]
Si es que te levanta ese error, debe se porque el usuario d epostgres que usas no tiene el mismo nombre que el usuario de tu sistema.

En algunos sistemas operativos, postgres viene configurado con `peer authentication` lo cual exige que uses un usuario con ese nombre.

**Comment by imant1** [comment]
Cuando te refieres al usuario de mi sistema, es el nombre de usuario que puse cuando se inicié ubuntu/wsl por primeras vez o al nombre de usuario de Windows? Si el usuario de ubuntu/wsl, entonces cómo puedo hacer para cambiarlo?

**Comment by meretamal** [comment]
Me refiero al de ubuntu. Creo que es más fácil si es que creas un nuevo usuario de postgres.

**Comment by imant1** [comment]
Empecé a seguir los pasos de nuevo desde el 7 y me fijé que me tiró un comentario que a ti @meretamal no te salió

![image](https://user-images.githubusercontent.com/64439029/112679240-b1fffd80-8e4a-11eb-836e-050e5959a2e3.png)

Dice "could not change directory to "/root": Permission denied"
¿Importa eso?

**Comment by meretamal** [comment]
Por mientras ignóralo

**Comment by imant1** [comment]
El tema es que en el siguiente paso (`CREATE USER myuser WITH SUPERUSER PASSWORD 'mypassword';`) debo poner mi username y contraseña. Pero cuando pongo el comando `whoami` me devuelve `root`, pero ¿me debería devolver el username que le puse la primera vez que inicié ubuntu (en mi caso `mantor`) o está bien que me devuela root? 
¿En vez de `myuser` tengo que poner `mantor` o `root`?

**Comment by msmendoza** [comment]
@ignaciomansuy Si es q aún no solucionas tu problema, podrías mandar un screenshot de tu `.env` y tu `Gemfile` en la línea 41. Finalmente un screenshot de qué aparece cuando realizas los siguientes pasos (solo el output final) [esto nos ayudará más a identificar el problema]:

1. Ejecuta `rails c` en la carpeta raíz del proyecto
2. tipea `ENV["DB_USER"]`
3. Manda el output

Cabe destacar que en `database.yml` el nombre de tu database de desarrollo debe estar dentro de tus bases creadas en postgres, caso contrario, debes ejecutar el comando `rails db:create` antes del `rails s`.

**Comment by imant1** [comment]
Hola @msmendoza, gracias por responder. Aquí los screenshots que me pediste:

1) `.env`
![image](https://user-images.githubusercontent.com/64439029/112733566-7420d900-8f1f-11eb-8c77-86fdd4065dae.png)

2) `Gemfile`
![image](https://user-images.githubusercontent.com/64439029/112733579-869b1280-8f1f-11eb-8ade-e36399dafdc8.png)

3) output `ENV["DB_USER"]`
![image](https://user-images.githubusercontent.com/64439029/112733702-412b1500-8f20-11eb-87ba-31eb21222250.png)

**Comment by imant1** [comment]
Hola @meretamal, estaba pensando que quizás lo más fácil sea desinstalar wsl y ubuntu y hacer todo el proceso de instalación desde cero. Quería saber si crees que es una buena idea hacer esto.

**Comment by martin-santiago** [comment]
Hola! tengo el mismo problema, al ejecutar rails s, lo han logrado resolver?
![imagen](https://user-images.githubusercontent.com/69615662/113369099-d66e4500-9336-11eb-92bc-9161b1212026.png)

**Comment by martin-santiago** [comment]
> 
> 
> Hola @meretamal, estaba pensando que quizás lo más fácil sea desinstalar wsl y ubuntu y hacer todo el proceso de instalación desde cero. Quería saber si crees que es una buena idea hacer esto.

pudiste resolverlo amigo?

**Comment by imant1** [comment]
Hola @martin-santiago, no, por mi parte tuve que desinstalar WSL y Ubuntu para realizar el proceso desde cero. Pero ahora estoy con otro problema en otro paso de la instalación.

**Comment by Pablomaluk** [comment]
@ignaciomansuy @martin-santiago tuve el mismo problema. Fue porque instale el rails, bundle install y rvm con sudo (se crea en carpeta root y despues necesita permisos de administrador para todo y ademas de que el path queda mal). Prueben a sacar las carpetas de rvm, gem y bundle del path root y moverlas a su usario y ver si funciona
