### ISSUE TITLE
Link para crear nueva asociación.

### ISSUE THREAD

**Issue by mc-cari** [IIC2143-2021-1/Syllabus#124]
Hola, cual seria la mejor forma de usar el form para crear una asociación en un link a parte?, por ejemplo, en el proyecto de ejemplo se para crear procesos de vacunaciones se hace render del form dentro de la misma página, pero lo quisiera realizar en otro link.

**Comment by Baelfire18** [comment]
No entiendo la pregunta quieres que el form te lleve a otra parte? Hacerlo en otra parte? O como?

**Comment by mc-cari** [comment]
Hacer el form en otra parte con un link_to y no un render
