### ISSUE TITLE
Problema deploy heroku  Bundler Output: /usr/bin/env: ‘ruby\r’: No such file or directory

### ISSUE THREAD

**Issue by diegobustosk** [IIC2143-2021-1/Syllabus#125]
Tenemos el proyecto listo pero a la hora de intentar hacer el deploy nos arroja el siguiente error.

![Captura de Pantalla 2021-05-06 a la(s) 22 06 20](https://user-images.githubusercontent.com/45362040/117387678-4c764680-aeb7-11eb-8220-d1a94ebd55db.png)
![Captura de Pantalla 2021-05-06 a la(s) 22 06 39](https://user-images.githubusercontent.com/45362040/117387698-5730db80-aeb7-11eb-9e8f-1791109aee8a.png)

**Comment by fjaraneda** [comment]
Estoy en las mismas :(
