### ISSUE TITLE
Error con ActiveAdmin:  ActiveRecord::StatementInvalid in ActiveAdmin::Devise::SessionsController#create

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2143-2021-1/Syllabus#129]
Hola, estaba tratando de crear el admin con la gema y al logear con el usuario y contraseña del admin y tira el siguiente error. He tratando varias veces ya, con distintas ramas, comandos y siempre me tira el mismo error (en MACOS)
![Screen Shot 2021-05-30 at 5 51 53 PM](https://user-images.githubusercontent.com/69609564/120121119-b9f05c80-c16f-11eb-9c17-65b65244372f.png)

**Comment by jmndoza** [comment]
@conyfernandezt Hola,lo pudiste resolver? Intenta hacer drop de la base de datos, luego create y correr las migraciones.
