### ISSUE TITLE
Error running '__rvm_make -j8' al hacer el paso 4

### ISSUE THREAD

**Issue by franancic** [IIC2143-2021-1/Syllabus#13]
Al tratar de instalar Ruby 2.6 con el comando "rvm install 2.6" me dice:
**Error running '__rvm_make -j8',
please read /Users/franancic/.rvm/log/1616774075_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.**
<img width="647" alt="Captura de Pantalla 2021-03-26 a la(s) 13 07 45" src="https://user-images.githubusercontent.com/62265851/112660513-4dd23f00-8e34-11eb-9ae1-0b9b0c9ab268.png">
Trate de buscar solución por internet, reiniciar computador, reiniciar la terminal, y me sigue apareciendo el mismo error:(

**Comment by mjvarela** [comment]
Hola @franancic ! Encontré dos posibles soluciones 

1. 
```
rvm pkg install openssl
rvm remove 2.6.6
rvm install 2.6.6 -C --with-openssl-dir=$HOME/.rvm/usr
```
2.
`sudo mv /usr/local/include /usr/local/include_old`
y después prueba `rvm install 2.6`

Cuéntame como te va!

**Comment by franancic** [comment]
Hola! la primera solución no me funcionó, me salió el mismo error, pero con la segunda si funciono! muchas gracias🥳

**Comment by mjvarela** [comment]
👍  denada!
