### ISSUE TITLE
Problemas al settear WSL 2 como versión default

### ISSUE THREAD

**Issue by tcouso** [IIC2143-2021-1/Syllabus#14]
Hola!

Estoy teniendo problemas con el paso 5 de la guía de instalación de WSL (https://docs.microsoft.com/en-us/windows/wsl/install-win10). Ya descargué WSL 2 según los requisitos de mi computador, pero al correr el comando `wsl --set-default-version 2` me aparece el siguiente error:

**wsl : El término 'wsl' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable.
Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que dicha ruta es correcta e
inténtelo de nuevo**

He intentado incluir una ruta de acceso, pero de momento no he tenido éxito, de modo que agradezco cualquier ayuda a este respecto.

Saludos!

**Comment by Daniel-SebastianGaete** [comment]
Hola Tomás, no sé de qué tipo es tu CPU, pero Microsoft señala que en máquinas con ARM64 si corres el comando desde PowerShell te va levantar ese error y que en cuyo caso debes usar `wsl.exe` desde PowerShell Core en lugar de `wsl`. Por otra parte, puede que necesites activar WSL desde PowerShell (ejecutado como admin) usando el comando `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`.
Cuéntame como te va con eso.
Saludos

**Comment by tcouso** [comment]
Hola @Daniel-SebastianGaete,
Mi CPU es de tipo x64. Probé con el comando el comando `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux` y pareciera ser que pasó algo, pero luego al intentar settear WSL 2 estoy teniendo el mismo error de antes. Tengo dudas con dónde debiera estar el archivo de WSL ¿Hay que incluirlo en alguna variable de entorno, o algo así? Quedo atento, Saludos

**Comment by meretamal** [comment]
Hola 😁

Después del paso 3 de la instalación de WSL. reiniciaste tu pc?

**Comment by tcouso** [comment]
Hola,

Tuve que habilitar la máquina virtual a mano desde el inicio en su momento, lo hice hace un rato así que cuando lo volví a intentar hoy no corrí ese comando. Si lo hice a mano ¿igual es necesario ejecutar esa parte en la consola?

**Comment by tcouso** [comment]
Hice todo de nuevo reiniciando el pc en el paso 3 y todo siguió igual

**Comment by Daniel-SebastianGaete** [comment]
Para instalar WSL ¿Actualizaste tu sistema operativo con Windows Insider? Encontré a alguien en internet que solucionó el problema actualizando el sistema operativo a la última versión Windows Insider

**Comment by tcouso** [comment]
Nop, no he actualizado a Windows insider. En su momento lo consideré pero me dio cosa, no pasa nada?

**Comment by Daniel-SebastianGaete** [comment]
Yo instalé WSL mediante eso. A la larga no pasó nada pero las primeras veces que encendí el pc luego de actualizarlo quedaba un rato pegado luego de ingresar la clave. Aparte de ese comportamiento raro no pasó nada.
En general seguí [esta guía](https://www.youtube.com/watch?v=jOPrNULaOIQ) para la instalación del WSL, por si la quieres revisar.

**Comment by tcouso** [comment]
Muchas gracias por la guía y la recomendación de windows insider! Pude echar todo a andar ahora sin problemas 😄 
Me está pasando lo mismo de quedar un rato pegado al iniciar sesión, eso después te dejó de pasar? 
Saludos!!

**Comment by Daniel-SebastianGaete** [comment]
Sí me dejó de pasar luego de unas cuantas reiniciadas. Me alegra que esté funcionando todo bien ahora :)
Saludos
