### ISSUE TITLE
Problema: "Your Ruby version is 2.6.6, but your Gemfile specified 2.7.0"

### ISSUE THREAD

**Issue by vikicontardo** [IIC2143-2021-1/Syllabus#15]
Hola, creo que esto cae en la categoría de _"ayua"._ La verdad googlee harto antes de publicar acá, pero tampoco quiero embarrarla poniendo cosas que no son... no he pillado nada en stackoverflow que me sirva para resolver esto.

**Básicamente mi problema es el del asunto de esta issue... adjunto imagen a continuación.**
![image](https://user-images.githubusercontent.com/53794587/112662945-06997d80-8e37-11eb-9c85-e5af4ecaa4a3.png)

No puedo terminar la guía de instalación para ubuntu, **al llegar al paso 10 muere.**

Gracias de antemano!!!

**Comment by meretamal** [comment]
Hola :grin:

Eso es porque antes **myapp** se creó usando ruby 2.7.0 (por el problema que solucionamos en la ayudantía).

Ahora que rvm si te funciona y estás usando la versión correcta de ruby, crea un nuevo proyecto con `rails new` y trabaja en ese

**Comment by vikicontardo** [comment]
Efectivamente eso era!! Te pasaste Moises <3
LOGRADO :partying_face: 
![image](https://user-images.githubusercontent.com/53794587/112665812-372ee680-8e3a-11eb-8955-b2394a51768e.png)

MIL GRACIAS!!!
