### ISSUE TITLE
Error mimemagic en Mac

### ISSUE THREAD

**Issue by fjaraneda** [IIC2143-2021-1/Syllabus#16]
Hola!
Al hacer el ``rails new myapp --database=postgresql`` en un momento me tira un error al crear la gema de mimemagic.
Error:
<img width="1163" alt="Captura de Pantalla 2021-03-26 a la(s) 13 47 13" src="https://user-images.githubusercontent.com/30665384/112665423-cdaed800-8e39-11eb-95ed-347cdf42212c.png">

Luego cuando corro el comnado ``gem install mimemagic -v '0.3.9' --source 'https://rubygems.org/'``

<img width="1177" alt="Captura de Pantalla 2021-03-26 a la(s) 13 50 07" src="https://user-images.githubusercontent.com/30665384/112666775-495d5480-8e3b-11eb-9743-b977da9b7919.png">

Si pueden ayudar se los agradezco !

**Comment by fbpesenti** [comment]
Hola @fjaraneda,

Prueba en tu archivo Gemfile cambiando la linea de codigo de mimemagic por la siguiente:

`gem 'mimemagic', github: 'mimemagicrb/mimemagic', ref: '01f92d86d15d85cfd0f20dabd025dcbd36a8a60f'`

Y luego en la terminal ejecuta  `bundle install` y `bundle update`

Sino te funciona intenta con la respuesta de la issue #9 

Saludos,

**Comment by fjaraneda** [comment]
Muchas gracias @fbpesenti , me sirvió la respuesta la issue #9 , y pude terminar la guia sin problemas.
