### ISSUE TITLE
Could not find a JavaScript runtime

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2143-2021-1/Syllabus#18]
Holaa 😄, 
El día de hoy logré completar el paso 11 y que todo funcionará bien en mi servidor, luego cerré este utilizando `CTRL + C` para terminar el proceso y trate de volver a ingresar `rails s` sin embargo ahora no me funciona y me arroja lo siguiente:

![image_2021-03-27_142000](https://user-images.githubusercontent.com/62019329/112728747-82fb9180-8f07-11eb-83d8-095e8728705f.png)

**Comment by meretamal** [comment]
Hola, tal como dice el error, no está encontrando un Runtime de JavaScript (por eso les pedimos instalar node).

Si corres `node -v` que te da de _output_?

**Comment by Mamunoz42** [comment]
zsh: command not found: node

Es raro porque seguí la guía al pie de la letra. PodrÍa afectar que esté utilizando la windows terminal que descargue de WindowStore en vez de ubuntu como tal?

**Comment by meretamal** [comment]
Si abres directamente ubuntu, e intentas correr ese comando, qué te aparece?

**Comment by Mamunoz42** [comment]
Me aparece el mismo error, incluso si utilizo el comando nvm tampoco me sale, pese a que antes de cerrar la consola (Cuando lo hice  por primera vez) si me funcionaba

**Comment by meretamal** [comment]
Y si corres `nvm -v`?

**Comment by Mamunoz42** [comment]
Ahora volví a instalar el node y me funciona, pero a que se debe que se haya "desinstalado"

**Comment by Mamunoz42** [comment]
> Y si corres `nvm -v`?

v14.16.0

**Comment by meretamal** [comment]
Encuentro un poco raro que te haya pasado eso. Lo único que se me viene a la mente es que, como ahora estás usando `zsh`, tal vez antes seguiste la instalación usando `bash` y, al hacer el cambio, tuviste problemas con el PATH.

**Comment by Mamunoz42** [comment]
Lo que pasa es que todos los pasos de la guía de instalación los lleve a cabo una vez tuve instalada la `zsh`. Por ejemplo ahora logre correr el servidor, sin embargo si abro otra consola de ubuntu y hago `node -v` o `nvm -v` me tira el mismo error 😢.

**Comment by meretamal** [comment]
Si ejecutas `ls -a` desde el directorio en el que estás al abrir ubuntu, debería aparecer que tienes un archivo llamado `.zshrc`.

Ábrelo y agrega:

```
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
```

Y luego trata de ver si funciona al cerrar y abrir tu terminal de nuevo

**Comment by Mamunoz42** [comment]
Ahora siiiii, muchísimas gracias 🎉 , cual es el error que cometí?

**Comment by meretamal** [comment]
Ni uno, a veces no se logra agregar `nvm` al path con su instalación, así que hay que hacerlo manual

**Comment by Mamunoz42** [comment]
Aaaaah, lo que yo hacia era correr esas líneas, no agregarlas al directorio que me habías especificado. Muchísimas gracias, te pasaste 👍🏽
