### ISSUE TITLE
rails s: Webpacker configuration file not found

### ISSUE THREAD

**Issue by fran-gl** [IIC2143-2021-1/Syllabus#19]
Hola! Al ejecutar ```rails s``` en la consola me aparece lo siguiente
![Captura de Pantalla 2021-03-27 a la(s) 14 31 35](https://user-images.githubusercontent.com/62031688/112729310-42e9de00-8f0a-11eb-85b5-4a967fa92dc9.png)
![Captura de Pantalla 2021-03-27 a la(s) 14 32 00](https://user-images.githubusercontent.com/62031688/112729314-454c3800-8f0a-11eb-9fd6-a2913c7e1652.png)
![Captura de Pantalla 2021-03-27 a la(s) 14 32 22](https://user-images.githubusercontent.com/62031688/112729316-467d6500-8f0a-11eb-8fc9-e4ce33c7b91e.png)
![Captura de Pantalla 2021-03-27 a la(s) 14 32 46](https://user-images.githubusercontent.com/62031688/112729317-4715fb80-8f0a-11eb-9a2c-f76960109d04.png)
Pido por favor si me pueden ayudar. Muchas gracias de antemano.

**Comment by meretamal** [comment]
Hola, según lo que se ve en tu terminal, creaste un proyecto usando Rails 6, el cual usa `webpacker` y te está levantando ese error ya que el _setup_ para esa versión de rails no estpa completo aún.

Usando Rails 5.2 (como sale en la guía) no deberías tener ese error

**Comment by fran-gl** [comment]
Ok, muchas gracias. Hay una forma de cambiar la versión de Rails que estoy ocupando?

**Comment by meretamal** [comment]
Podrías desinstalar `rails` y `railties` ejecutando `gem uninstall rails` y `gem uninstall railties`, y luego podrías instalar la versión correcta de rails.

Otra solución es usar [gemsets](https://rvm.io/gemsets/basics)

**Comment by fran-gl** [comment]
Perfecto, muchísimas gracias! Ahora me funcionó todo correctamente. Me disculpo por las molestias.
