### ISSUE TITLE
Error "This update only applies to machines with the Windows Subsystem for Linux"

### ISSUE THREAD

**Issue by myndr1** [IIC2143-2021-1/Syllabus#2]
¡Holaa! En este paso me aparece el siguiente error, he intentado algunas cosas pero aún no he podido resolverlo, alguna idea de que puedo hacer?:(

![SmartSelectImage_2021-03-22-12-14-17](https://user-images.githubusercontent.com/62078553/112012934-9d90cd80-8af7-11eb-8450-5138474230a0.png)

![SmartSelectImage_2021-03-22-12-14-37](https://user-images.githubusercontent.com/62078553/112012955-a1bceb00-8af7-11eb-8e7c-2ce69923c81a.png)

**Comment by meretamal** [comment]
Hola 😁 

Luego del paso 3 reiniciaste tu pc?

**Comment by myndr1** [comment]
no lo había reiniciado, muchas gracias!!!
