### ISSUE TITLE
Setup del proyecto en windows 8 

### ISSUE THREAD

**Issue by jnbaltra** [IIC2143-2021-1/Syllabus#20]
Hola, estaba leyendo la guía de instalación para el setup del proyecto, pero al parecer solo se puede hacer para windows 10, que puedo hacer en caso de tener window 8.1 en mi computador?

**Comment by meretamal** [comment]
Hola 😁, por fabor háblame por telegram para coordinarnos y poder ayudarte directamente con la instalación de todos los programas que vamos a usar. Mi usuario es @meretamal
