### ISSUE TITLE
FATAL: Peer authentication failed

### ISSUE THREAD

**Issue by nicolascruzi** [IIC2143-2021-1/Syllabus#21]
Me aparece el siguiente error en el paso de crear la base de datos 
FATAL:  Peer authentication failed for user "myuser"
Ayuda, incluso revisando las issues descargue la gema para leer archivos .env recomendada en una issue anterior

**Comment by crvargasu** [comment]
Hola!

El problema es un error en la autenticación de postgres. Seteaste el valor de DB_PASSWORD en el archivo **.env** ?

**Comment by meretamal** [comment]
Hola 😁 , el problema es que estás usando el usuario "myuser" que pusimos como ejemplo en la guía de _setup_, sin embargo, tal como dice ahí, este se debe llamar igual al usuario de tu sistema. Eso lo hacemos así para evitar este mismo error que te aparece ahora.

**Comment by Sweinzierl28** [comment]
Hola! Yo tengo Mac y apenas ejecuto "psql postgres" para ingresar, me pide la contraseña del usuario "Mac" y como nose a cual se refiere me tira este mismo error. Se creó un usuario automático con el nombre de mi computador? Cómo hago para saber la contraseña o crearme otro propio? 

Macs-MacBook-Pro-2:~ Mac$ brew services start postgresql
Service `postgresql` already started, use `brew services restart postgresql` to restart.
Macs-MacBook-Pro-2:~ Mac$ psql postgres
Password for user Mac: 
psql: error: FATAL:  password authentication failed for user "Mac"
Macs-MacBook-Pro-2:~ Mac$ CREATE USER SWeinzierl28 WITH SUPERUSER PASSWORD 'XXX';
-bash: CREATE: command not found
Macs-MacBook-Pro-2:~ Mac$

**Comment by meretamal** [comment]
Hola @Sweinzierl28, como el problema original de esta issue es distinto al tuyo, voy a cerrarla, te pido que por favor abras una nuevas explicando tu situación para poder ayudarte
