### ISSUE TITLE
Problema gem virtual box

### ISSUE THREAD

**Issue by FCamaggi** [IIC2143-2021-1/Syllabus#22]
Al hacer el setup en Virtual box, ubuntu, en el paso 5 luego de hacer correctamente "rvm install 2.6", en el momento de usar "gem install rails -v 5.2.4" aparece lo siguiente:

![photo_2021-03-27_20-39-26](https://user-images.githubusercontent.com/61996131/112737864-89583080-8f3c-11eb-8050-f279d6750e51.jpg)

Para luego de usar alguna de las opciones dadas, salir errores, he hecho el setup varias veces ya y se produce el error desde que intento hacerlo en virtual box

**Comment by meretamal** [comment]
Si corres `ruby -v` que te sale?

**Comment by FCamaggi** [comment]
![image](https://user-images.githubusercontent.com/61996131/112738144-f10f7b00-8f3e-11eb-91f4-a25ce6a93bea.png)

**Comment by meretamal** [comment]
Y si corres `rvm -v`?

**Comment by FCamaggi** [comment]
![image](https://user-images.githubusercontent.com/61996131/112738201-6d09c300-8f3f-11eb-85b0-158d122a130c.png)
 
Al hacer "rvm install 2.6" sale esto

![image](https://user-images.githubusercontent.com/61996131/112738222-a6dac980-8f3f-11eb-8417-cadbef12ad70.png)

Donde sale que se generaron las gems o no?

**Comment by FCamaggi** [comment]
Al usar "rvm install 2.6" sale

![image](https://user-images.githubusercontent.com/61996131/112738626-51082080-8f43-11eb-8346-57c9fcf4ac5d.png)

Confirmando que tengo ya ruby instalado

**Comment by franciscobalmaceda** [comment]
Tengo el mismo problema, lograste solucionarlo?

**Comment by FCamaggi** [comment]
Noup, aún nada

**Comment by Pablo-Carrasco** [comment]
Holaa, me pasó algo parecido, sí me reconocía ruby al correr `ruby -v`, pero se me caía al correr `gem install rails -v 5.2.4` arrojando el siguiente error:
![Error rails install](https://user-images.githubusercontent.com/62043814/112933830-f31c3a00-90f6-11eb-840a-03a378a300b5.png)
Buscando encontré [esta guía](https://gorails.com/setup/ubuntu/14.04) y cuando intenté correr `rvm use 2.6` me arrojó un error de que tenía que hacer login en el bash (o algo así) y me mandó a [esta página](https://rvm.io/integration/gnome-terminal), simplemente corrí lo que decía la terminal, es decir, `/bin/bash --login` y después de eso me dejó setear la versión de ruby que quería utilizar. Adjunto imagen.
![Solucion rails](https://user-images.githubusercontent.com/62043814/112934175-92413180-90f7-11eb-966a-9b8363963799.png)
El problema según yo está en que no se le define al sistema qué ruby utilizar, al correr `rvm current` revisamos qué versión estamos utilizando, pero a mi me salía _system_ por lo que creo que me faltaba setear eso correctamente, quizás es algo parecido contigo pero de igual manera lo dejo por si a alguien le llega a servir.
PD: Estoy corriendo todo en Lubuntu 'nativo', no es máquina virtual ni WSL, espero puedan arreglarlo!!

**Comment by FCamaggi** [comment]
> Holaa, me pasó algo parecido, sí me reconocía ruby al correr `ruby -v`, pero se me caía al correr `gem install rails -v 5.2.4` arrojando el siguiente error:
> ![Error rails install](https://user-images.githubusercontent.com/62043814/112933830-f31c3a00-90f6-11eb-840a-03a378a300b5.png)
> Buscando encontré [esta guía](https://gorails.com/setup/ubuntu/14.04) y cuando intenté correr `rvm use 2.6` me arrojó un error de que tenía que hacer login en el bash (o algo así) y me mandó a [esta página](https://rvm.io/integration/gnome-terminal), simplemente corrí lo que decía la terminal, es decir, `/bin/bash --login` y después de eso me dejó setear la versión de ruby que quería utilizar. Adjunto imagen.
> ![Solucion rails](https://user-images.githubusercontent.com/62043814/112934175-92413180-90f7-11eb-966a-9b8363963799.png)
> El problema según yo está en que no se le define al sistema qué ruby utilizar, al correr `rvm current` revisamos qué versión estamos utilizando, pero a mi me salía _system_ por lo que creo que me faltaba setear eso correctamente, quizás es algo parecido contigo pero de igual manera lo dejo por si a alguien le llega a servir.
> PD: Estoy corriendo todo en Lubuntu 'nativo', no es máquina virtual ni WSL, espero puedan arreglarlo!!

Me funcionó siguiendo lo que dices, `/bin/bash --login`  seguido de `rvm use 2.6` y luego `gem install rails -v 5.2.4`, muchas gracias

**Comment by FCamaggi** [comment]
encontré una manera mas fácil al menos para mi programa, entrar aqui:

![image](https://user-images.githubusercontent.com/61996131/113001971-ba588100-9147-11eb-902b-5e3a6253492a.png)

Luego:

![image](https://user-images.githubusercontent.com/61996131/113002133-de1bc700-9147-11eb-8eb6-30102943e149.png)

y hacer check aquí

![image](https://user-images.githubusercontent.com/61996131/113002214-f1c72d80-9147-11eb-9960-b650c173d7e3.png)

Luego al abrir otro terminal ya podemos correr rvm use sin problema

**Comment by franciscobalmaceda** [comment]
desinstale y volvi a instalar rvm y con eso se me borraron los comandos de /.profile y de /.bash_profile por lo que tampoco me sirvio el /bin/bash --login. Mi solucion fue agregar el siguiente comando [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"  a  /.bashrc que es en donde busca los comandos sin el login. Ahora funciona bien

**Comment by FCamaggi** [comment]
A mi me funcionó todo bien hasta acá

![image](https://user-images.githubusercontent.com/61996131/113008104-1ffb3c00-914d-11eb-8220-4eaeaf576e62.png)

Según yo debería instalar mas cosas que solo eso

**Comment by Pablo-Carrasco** [comment]
Eso pasa porque no tienes git instalado, me paso lo mismo...
Intenta `git -v` y te dirá que no lo tienes arrojandote un comando para instalarlo que es como `sudo apt install git` o algo así...

**Comment by FCamaggi** [comment]
Efectivamente era eso, gracias, ahora si que si funcionó
