### ISSUE TITLE
Consulta requisito min. de desarrollo [4.1]

### ISSUE THREAD

**Issue by msmendoza** [IIC2143-2021-1/Syllabus#23]
Se menciona que se debe utilizar el servicio _Kanban Trello_ para organizar el trabajo de equipo. De la misma forma la plataforma GitHub donde todos guardaremos nuestros proyectos admite una nueva _feature_ llamada _Projects_ donde se puede establecer un Kanban automatizado que se sincroniza con las _issues_ de cada proyecto,  se asignan trabajos y blablá... funcionando igual (mejor a mi parecer) que Trello.

Sería posible utilizarlo en reemplazo de **Trello**? (obviamente el _PO_ tendría acceso)

Aquí va un preview:

![image](https://user-images.githubusercontent.com/31081657/112755080-864d5680-8fb5-11eb-94e0-07b76b2f5d44.png)

Muchas gracias de antemano!

**Comment by meretamal** [comment]
Hola @msmendoza 😁 

Pueden discutirlo directamente con su _product owner_. La verdad es que yo también las prefiero, ya que te permite hacer el seguimiento de tu app fácilmente mediante _issues_, a las cuales les puedes asignar un encargado y _labels_ (y si se ponen a usar pull requests... otro nivel 🚀 ).

Eso si, _Trello_ también te ofrece distintas herramientas que _Github Projects_ no, por lo que sería bueno analizar a qué nivel quieren uitilizar su tablero _Kanban_.

Véanlo 👀  bien en su reunión inicial.

**Comment by msmendoza** [comment]
perfect, gracias @meretamal! Ahí lo vemos entonces 🙌🏽
