### ISSUE TITLE
Paso 9: ¿Cómo se abren otros editores de texto?

### ISSUE THREAD

**Issue by jorge-schenke** [IIC2143-2021-1/Syllabus#24]
En la ayudantía nos mostraron cómo abrir el directorio con VSCode, usando el comando code .
¿Cómo se hace si tengo otro editor de texto? (En mi caso sublime, instalado en Windows) hay que instalar el editor en Ubuntu?.
Gracias!

**Comment by Crespy98** [comment]
Hola prueba con `subl .` , encontré la información en esta pagina https://jonalvarezz.com/articles/abrir-una-carpeta-o-archivo-en-sublime-desde-la-terminal/
