### ISSUE TITLE
Paso 6: Problemas con gemfile en bundle install 

### ISSUE THREAD

**Issue by IgnaciaJ** [IIC2143-2021-1/Syllabus#25]
Hola! Luego de crear mi carpeta, al ejecutar bundle install me arroja el siguiente error:
<img width="612" alt="Captura de Pantalla 2021-03-28 a la(s) 16 41 10" src="https://user-images.githubusercontent.com/69643709/112765629-6f722880-8fe4-11eb-837f-2850c8fabc35.png">
He intentado de arreglarlo corriendo el comando que está en rojo pero sigue sin funcionarme.
Gracias!!

**Comment by meretamal** [comment]
Hola 😁 

Cómo instalaste `postgres`?

**Comment by IgnaciaJ** [comment]
Holaaa con lo de la guía del set up para mac!

**Comment by IgnaciaJ** [comment]
Hola Moises! Acabo de arreglar mi problema era algo del homebrew! Muchas gracias igual

**Comment by gaspcr** [comment]
@IgnaciaJ De casualidad cómo lograste arreglarlo?, tengo el mismo problema al crear las dependencias con rails new

**Comment by IgnaciaJ** [comment]
Hola @gaspcr!! actualice mi computador(si teni mac actualiza a la última versión) y despues volvi a instalar el homebrew! cuando se te instale vuelve a intentar el paso 6

**Comment by ignaciomansuy** [comment]
Hola @IgnaciaJ, tengo el mismo problema, a qué te refieres con instalar el homebrew?
