### ISSUE TITLE
Paso 4: Failed to build gem native extension.

### ISSUE THREAD

**Issue by claudiaconcham** [IIC2143-2021-1/Syllabus#26]
Hola!! tuve un problema al ejecutar el segundo comando del paso 4: ```gem install rails -v 5.2.4``` ,  la consola me recomendaba instalarlo con ```sudo gem install rails```, pero se me instaló la version 6.1 , así que lo desinstalé con ```sudo gem uninstall rails``` ```sudo gem uninstall railties```, pero sigue sin funcionarme el comando anterior. 

![Captura de pantalla 2021-03-29 a la(s) 09 37 18](https://user-images.githubusercontent.com/69604960/112840216-71d09300-9075-11eb-8f6e-12dbd0571d79.png)

No sé si quedó correctamente desinstalado, ni qué hacer para instalar la versión que se recomienda en la guía. 
Lo otro es que, seguí con los pasos del set up, pero no me funcionaba la parte del  http://localhost:3000/, así que ahí desinstalé rails, influye en algo esto? o sólo tengo que repetir el procedimiento una vez que instale la versión correcta??

**Comment by meretamal** [comment]
Hola, por favor revisa la issue #9 y dime si te funciona 😁

**Comment by claudiaconcham** [comment]
Si!! ahí me funcionó ! Sorry, juraba que había leído bien todas las issues 😢 
Muchas gracias!!!
