### ISSUE TITLE
Error con instalacion de Ruby con rails s

### ISSUE THREAD

**Issue by diegobustosk** [IIC2143-2021-1/Syllabus#28]
Hola estoy teniendo problemas con las instalaciones. Segui el paso a paso al pie de la letra pero no me deja hacer el rails s (dice que hay problemas con webpack) . Ademas cuando ingreso al repo nuevo me dice que no tengo instalado ruby, pero si corro ruby -v me dice que si existe en el computador. Estoy usando mac y zsh. 

Error con 'rails s' => Traceback (most recent call last): ... ( : Webpacker configuration file not found /Users/diegobustos/Desktop/Universidad/4-semestre/Ing_software/proyecto/myapp/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/diegobustos/Desktop/Universidad/4-semestre/Ing_software/proyecto/myapp/config/webpacker.yml (RuntimeError)

Error con ruby  => rvm install "ruby-2.6.3" =>    Error: Permission denied @ apply2files - /usr/local/lib/node_modules/vercel/node_modules/term-size/vendor/macos/.DS_Store
Requirements installation failed with status: 1

**Comment by jmndoza** [comment]
Hola @diegobustosk, 
probaste `run rails webpacker:install ` ?

**Comment by diegobustosk** [comment]
Hola si lo probe pero me dice que hay problemas con yarn. Tampoco me deja correr ruby dice que no existe el comando pero si existe cuando hago ruby -v

**Comment by crvargasu** [comment]
Hola, por favor revisa la issue [#19](https://github.com/IIC2143-2021-1/Syllabus/issues/19). 

El error puede ser dado que no instalaste la versión de rails correcta.

**Comment by diegobustosk** [comment]
Llevo varios días intentado y no me deja instalar la 5.2.4 pero si me deja instalar la 5.2.5 . Me arroja el siguiente error

> error`
![Captura de Pantalla 2021-04-04 a la(s) 23 48 22](https://user-images.githubusercontent.com/45362040/113535124-93170f00-95a0-11eb-8c78-503b9d9e4736.png)
`

**Comment by diegobustosk** [comment]
~/Desktop/Universidad/4-semestre/Ing_software/proyecto » sudo gem install rails -v 5.2.4
Building native extensions. This could take a while...
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/mimemagic-0.3.10/ext/mimemagic
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -rrubygems /Library/Ruby/Gems/2.6.0/gems/rake-13.0.3/exe/rake RUBYARCHDIR\=/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/mimemagic-0.3.10 RUBYLIBDIR\=/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/mimemagic-0.3.10
rake aborted!
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/opt/local/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.

This gem might be installed as a dependency of some bigger package, such as rails, activestorage,
axlsx or cucumber. While most of these packages use the functionality of this gem, some gems have
included this gem by accident. Set USE_FREEDESKTOP_PLACEHOLDER=true if you are certain that you
do not need this gem, and wish to skip the inclusion of freedesktop.org.xml.

The FREEDESKTOP_PLACEHOLDER option is meant as a transitional feature, and will be deprecated in
the next release.
/Library/Ruby/Gems/2.6.0/gems/mimemagic-0.3.10/ext/mimemagic/Rakefile:15:in `locate_mime_database'
/Library/Ruby/Gems/2.6.0/gems/mimemagic-0.3.10/ext/mimemagic/Rakefile:39:in `block in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<main>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/mimemagic-0.3.10 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/mimemagic-0.3.10/gem_make.out

**Comment by JosefaPaz** [comment]
Hola Diego! Instalando la versión 5.2.5 te funcionó todo bien?

Quedo atenta!

**Comment by diegobustosk** [comment]
Con esa versión esta perfect
