### ISSUE TITLE
Paso 4: error instalando ruby

### ISSUE THREAD

**Issue by dcastillo5** [IIC2143-2021-1/Syllabus#29]
Hola!
Estoy teniendo problema al ejecutar `rvm install 2.6` en Mac.  He intentado algunas cosas pero al final siempre me sale el mismo error :( 

![Captura de Pantalla 2021-03-29 a la(s) 11 27 20 a  m](https://user-images.githubusercontent.com/61330735/112868525-c548de00-9081-11eb-9193-e2258e238f8e.png)

**Comment by crvargasu** [comment]
Hola, intenta `rvm install “ruby-2.6.0”` y me cuentas

**Comment by dcastillo5** [comment]
Sale el mismo error

**Comment by crvargasu** [comment]
Intenta con alguno de estos

`rvm --debug requirements ruby`

`xcode-select --install`

**Comment by dcastillo5** [comment]
Probé ambas cosas y sigue el mismo error
![Captura de Pantalla 2021-04-01 a la(s) 11 22 02 a  m](https://user-images.githubusercontent.com/61330735/113325515-2d93fb80-92de-11eb-83fe-5d9ecf2707f5.png)

Para xcode probé desinstalando y volviendo a instalar asi :
`sudo rm -rf /Library/Developer/CommandLineTools`
` xcode-select --install`

**Comment by crvargasu** [comment]
Mmm, encontré esto tmbn 

primero debes correr

`sudo mv /usr/local/include /usr/local/include_old `

y después

`rvm install 2.5.0 --with-openssl-dir=/usr/local/opt/openssl/bin/openssl `

Acá puedes encontrar la fuente por si te sirve https://superuser.com/questions/1296016/rvm-error-running-configure
