### ISSUE TITLE
'FATAL: role "myusername" does not exist' al entrar al servidor de proyecto

### ISSUE THREAD

**Issue by MagnaThyrsus** [IIC2143-2021-1/Syllabus#3]
Holas

Siguiendo lo indicado en [la guía para instalar ruby en ubuntu para windows](https://github.com/IIC2143-2021-1/Syllabus/tree/main/Gu%C3%ADas/Setup/Ubuntu), procedí a crear un servidor para el proyecto que llame "prueba" y me aparece este error:
```
     rescue ::PG::Error => error
          if error.message.include?("does not exist")
            raise ActiveRecord::NoDatabaseError
          else
            raise
          end
```
El nombre de usuario que usé para crear el `superuser` de PostgreSQL es distinto al usuario que tengo para la consola de ubuntu. Tendrá eso que ver? y si no cuál es el problema?

**Comment by Crespy98** [comment]
como sale en el paso 7 debe tener el mismo nombre que el usuario del sistema
