### ISSUE TITLE
Problema al acceder al localhost, Paso 11

### ISSUE THREAD

**Issue by vichoruiz** [IIC2143-2021-1/Syllabus#30]
cuando corro el localhost:3000, me sale esto, no el Yay! You’re on Rails!

![imagen](https://user-images.githubusercontent.com/69742735/112931057-c87bb280-90f1-11eb-82dc-aa05d7a8c0db.png)

**Comment by Daniel-SebastianGaete** [comment]
Hola Vicente,
Revisa tu archivo `database.yml` y que la línea de adapter diga `adapter: postgresql` y revisa que tengas la gema `pg` en tu archivo `Gemfile`, que corresponde al adaptador al cual hacen referencia las dos primeras líneas del error. Si está en el `Gemfile` entonces puede que te falte hacer bundle install en la consola

**Comment by NelsonIMA** [comment]
Hola! Tengo un problema diferente con el localhost en MAC. Gracias de antemano :)

![Captura de Pantalla 2021-03-30 a la(s) 18 24 32](https://user-images.githubusercontent.com/42616922/113059249-9c117600-9185-11eb-93ed-06cf42a20da9.png)

**Comment by meretamal** [comment]
@NelsonIMA, dado que el error es distinto, te pido que crees una nueva _issue_, explicando que te está ocurriendo.

Por favor agrega más detalles, cómo por ejemplo, el _output_ de tu terminal.

**Comment by NelsonIMA** [comment]
Ya perfecto!
