### ISSUE TITLE
Uso de gema.

### ISSUE THREAD

**Issue by Huasito-Appel** [IIC2143-2021-1/Syllabus#31]
Hola, tienen una lista base de gemas prohibidas?
de forma particular, puedo usar  SUSPENDERS? ( https://github.com/thoughtbot/suspenders ).
es una gema generadora, bastante overkill creo, pero que quiero utilizar para acostumbrarme mas que otra cosa. Quedo atento

**Comment by meretamal** [comment]
Hola, se va a subir una issue con un listado de gemas permitidas. 

Por mientras te puedo decir que no se puede usar `suspender`
