### ISSUE TITLE
WslRegisterDistribution failed with error: 0x80370102

### ISSUE THREAD

**Issue by PDominguezW** [IIC2143-2021-1/Syllabus#32]
Descargue ubuntu, pero cuando abro la consola me muestra'
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.'
Que puedo hacer para arreglarlo?

**Comment by domingo2000** [comment]
Buena, a mi me pasó lo mismo, y lo que hice (que salia en los errores de la misma pagina de instalación) fue que tienes que meterte a la BIOS de tu computador, y activar en opciones avanzadas la opción de virtualización. Para meterte a la bios tienes que apretar una tecla tipo "Esc", "F2", "F8", "F12", depende de que fabricante sea tu notebook o placa madre del pc.

**Comment by PDominguezW** [comment]
Me funciono, gracias :)
