### ISSUE TITLE
Instalación Mac paso 8

### ISSUE THREAD

**Issue by RMMURUA** [IIC2143-2021-1/Syllabus#33]
Hola! quería pedir ayuda con un error que me sale al ejecutar rails db:create del paso 8 de la guia por favor. Me sale que no se encontró un javascript runtime pero no se a que se refiere. Mil gracias de antemano.
![Imagen 30-03-21 a las 16 35](https://user-images.githubusercontent.com/48321595/113046459-8052a380-9176-11eb-9bc0-d39df3ae6b74.jpg)

**Comment by meretamal** [comment]
Hola, si te fijas, cuando intentas moverte a la carpeta "nombre proyecto", sale que no existe.

Por favor asegúrate que, cuando corres `rails new`, se esté creando tu app.

**Comment by RMMURUA** [comment]
sii! es que al principio puse por error "poryecto" en vez de "proyecto" y por eso no encontraba la carpeta ajajsajjaj. Pero incluso despues de estar dentro de la carpeta correcta me arroja el error de arriba.

**Comment by RMMURUA** [comment]
Me acaba de funcionar luego de instalar node con
brew install nodejs
por si a alguien mas le sirve. Gracias de todas formas!
