### ISSUE TITLE
Orden Pokemones de entrenador Tarea Ruby

### ISSUE THREAD

**Issue by domingo2000** [IIC2143-2021-1/Syllabus#34]
Hola, no me queda claro bien el orden en que pelean exactamente los pokemones, entiendo que parte luchando el con mayor velocidad, pero me surgen varias dudas.
1) ¿El entrenador que no tenia el pokemón mas veloz (es decir que no era mas veloz que el del rival), también parte luchando con **su**  pokemón mas veloz, o parte luchando solo con el primero en su lista de pokemones?.
2) Ya finalizado un combate, ¿los pokemones siguen en el orden en que quedaron luego de terminado el combate anterior, o se mantiene el orden de la lista de pokemones del entrenador para todos los combates?

**Comment by CmPoblete** [comment]
Hola, 1) Los entrenadores siempre pelean segun el orden de sus 6 pokemones independiente de sus velocidades. Las velocidades afectan solamente para decidir si el entrenador 1 o el entrenador 2 comenzara atacando.

2) El combate no deberia afectar el orden de los pokemones, siempre se van a mantener segun la lista de pokemones del archivo entrenadores.csv
