### ISSUE TITLE
[Tarea] Duda con fórmula de vida actual y pokemones que más sobrevivieron

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2143-2021-1/Syllabus#35]
Hola, me surgieron dos dudas con el enunciado:

1) ¿Está bien la fórmula de la vida actual del pokemon defensor? ¿o faltan unos paréntesis? porque por cómo está escrita en el enunciado, cuando un pokemon es atacado, su defensa le resta vida.

2) Al crear el top de pokemones que más sobrevivieron ¿se debe agrupar a los pokemones por id? lo pregunto porque en el archivo `entrenadores.csv` hay ids de pokemones que corresponden a dos entrenadores y entonces sería posible contar cuántas veces sobrevivió cada pokemon con cierto id y que pertenece a cierto entrenador o contar cuántas veces cobrevivió cada pokemon de cierto id considerando a todos los entrenadores que tienen un pokemon con este id.

**Comment by CmPoblete** [comment]
Hola, 1) toda la razon, faltaron unos parentesis par que la defensa le reste al ataque. La idea era que fuera asi (APA - DAD/4) lo arreglaré.
2) Se debe agrupar por id, por ejemplo:
El entrenador 1 tiene al pokemon 1. Su pokemon 1 quedo vivo en 3 combates.
El entrenador 2 tambien tiene al pokemon 1. Su pokemon 1 quedo vivo en 1 combate.
Por lo tanto, el pokemon 1 sobrevivio a 4 combates. Espero que haya quedado claro

**Comment by sebacarrasco** [comment]
Muchas gracias! me quedó super claro
