### ISSUE TITLE
New encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)

### ISSUE THREAD

**Issue by PDominguezW** [IIC2143-2021-1/Syllabus#36]
Cuando trato de crear la base de datos de rails con el comando 'rails db:create', me manda el mensaje 'PG::InvalidParameterValue: ERROR:  new encoding (UTF8) is incompatible with the encoding of the template database (SQL_ASCII)'. Si corro el servidor con 'rails s' y entro a  http://localhost:3000/, la pagina me manda error de que no encontro la base de datos. ¿Como lo puedo arreglar?

**Comment by meretamal** [comment]
Hola 😁 

Qué versión de ubuntu tienes?

**Comment by PDominguezW** [comment]
16.04 LTS

**Comment by meretamal** [comment]
Lo que pasa es que desde la versión **18.04 para arriba**, la versión de `postgres` que instala por _default_ es, mínimo, la 10, cuyas bases de datos viene por _default_ con _encoding_ UTF-8.

Es probable que tengas la versión 9, que usa _encoding_ SQL_ASCII.

Si estás usando WSL, lo más fácil es instalar la versión 18.04 o 20.04 y hacer el _setup_ de nuevo.

**Comment by PDominguezW** [comment]
Muchas gracias :)
