### ISSUE TITLE
Error con webpacker.yml MAC

### ISSUE THREAD

**Issue by NelsonIMA** [IIC2143-2021-1/Syllabus#37]
Hola! Al ejecutar `rails s`, correspondiente al paso 9, me salen 2 errores relacionados al archivo `webpacker.yml`. A continuación los pantallazos en el orden correspondiente:

![Captura de Pantalla 2021-03-30 a la(s) 18 37 06](https://user-images.githubusercontent.com/42616922/113060569-34f4c100-9187-11eb-9f24-4080f5b5d437.png)

![Captura de Pantalla 2021-03-30 a la(s) 18 37 15](https://user-images.githubusercontent.com/42616922/113060615-44740a00-9187-11eb-8075-2f81a5e949cc.png)

Gracias de antemano!

**Comment by crvargasu** [comment]
Hola, revisa la issue [#19](https://github.com/IIC2143-2021-1/Syllabus/issues/19) y ve si funciona

**Comment by NelsonIMA** [comment]
Me fucionó! Sin embargo me llevó a un error el cuál lo resuelven acá #33 

Gracias ^^
