### ISSUE TITLE
Paso 6 MAC - command not found

### ISSUE THREAD

**Issue by NelsonIMA** [IIC2143-2021-1/Syllabus#38]
Hola!! Luego de ejecutar `rails new proy_software --database=postgresql` , me apareció esto:
![Captura de Pantalla 2021-03-30 a la(s) 17 55 41](https://user-images.githubusercontent.com/42616922/113056071-b6e1eb80-9181-11eb-8eb1-fefa62d9394f.png)

`sh: node: command not found
sh: nodejs: command not found
Node.js not installed. Please download and install Node.js https://nodejs.org/en/download/`

Cabe destacar que me funcionó todo lo demás, a excepción del paso 9, lo cual dejé en la issue #37 

¿Debería seguir el paso de instalar Node.js o no?

Gracias de antemano :)

**Comment by crvargasu** [comment]
Hola, te comenté la issue anterior. El problema al parecer es que creaste el proyecto usando rails 6 y no el 5.2 como sale en la guía. Revisa la issue anterior y dps sigues con la guia
