### ISSUE TITLE
[Tarea] Duda de qué sucede cuando el pokemon se muere

### ISSUE THREAD

**Issue by denisseleiva** [IIC2143-2021-1/Syllabus#39]
Holaaaa! Tengo una duda sobre qué sucede cuando el pokemon se muere. ¿La idea es que se eliminen los pokemones que mueren de la lista de pokemones disponibles para el entrenador? ¿O sólo se guarda en la instancia de Combate la lista de los pokemones vivos y se mantienen los pokemones de las instancias de Entrenador?
Otra cosa, cuando en el enunciado dice que los pokemones recuperan toda la vida perdida una vez finalizado el combate, esto aplica también para los pokemones muertos? 😅

Gracias :3

**Comment by CmPoblete** [comment]
La idea es que al finalizar el combate se guarden en la instancia de Combate los pokemones que quedaron vivos. Los pokemones que mueren no se deben quitar de la lista del entrenador.
Lo de los pokemones recuperan toda su vida perdida tambien aplica para los que murieron (reviven)

**Comment by denisseleiva** [comment]
super, gracias!!
