### ISSUE TITLE
Paso 6: Failed to connect to github.com port 443: Connection refused

### ISSUE THREAD

**Issue by gianlucafalcone** [IIC2143-2021-1/Syllabus#4]
Hola, al intentar ejecutar el comando del paso 6 me arroja lo siguiente:
fatal: unable to access 'http://github.com/nvm-sh/nvm.git': Failed to connect to github.com port 443: Connection refused
Failed to clone nvm repo. Please report this!

Si alguien puede ayudarme con resolver esta duda.

**Comment by JosefaPaz** [comment]
Hola! Qué versión de Git estás utilizando? ya que según el readme de nvm necesitas como mínimo la versión 1.7.10 

Quedo atenta 😄

**Comment by gianlucafalcone** [comment]
Holaa, tengo la versión:
git version 2.30.1.windows.1

**Comment by JosefaPaz** [comment]
Estuve revisando en otras issues hechas en github y stackoverflow 🧐 y al parecer el error 403 tiene que ver con las proxys, por lo que debes actualizarlas en Git.

Para realizar esto, las issues recomiendan que, si estás usando tu internet normal, corras el comando `git config --global http.proxy localhost:7078`. Por otro lado, si usas un servidor de proxy (esto lo puedes saber yendo a "configuración de proxy o proxy settings" y revisando si está clickeada la info de servidor de proxy) los pasos a seguir para saber qué poner en el comando los puedes encontrar aquí https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github.

Avisame qué te funciona o si sigues con el error! 😄

**Comment by meretamal** [comment]
Hola :grin: 
Puedes ejecutar `curl --verbose https://github.com`?

En el caso de que te levante algo como
```bash
* SSL connect error
curl: (35) SSL connect error
```
ejecuta `yum update -y nss curl libcurl`

**Comment by gianlucafalcone** [comment]
> Hola 😁
> Puedes ejecutar `curl --verbose https://github.com`?
> 
> En el caso de que te levante algo como
> 
> ```shell
> * SSL connect error
> curl: (35) SSL connect error
> ```
> 
> ejecuta `yum update -y nss curl libcurl`

Hola, no levantó ningun error.

**Comment by gianlucafalcone** [comment]
> Estuve revisando en otras issues hechas en github y stackoverflow 🧐 y al parecer el error 403 tiene que ver con las proxys, por lo que debes actualizarlas en Git.
> 
> Para realizar esto, las issues recomiendan que, si estás usando tu internet normal, corras el comando `git config --global http.proxy localhost:7078`. Por otro lado, si usas un servidor de proxy (esto lo puedes saber yendo a "configuración de proxy o proxy settings" y revisando si está clickeada la info de servidor de proxy) los pasos a seguir para saber qué poner en el comando los puedes encontrar aquí https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github.
> 
> Avisame qué te funciona o si sigues con el error! 😄

De este link ejecute lo siguiente:
```git config --global http.proxy "" ```

 luego corri el paso 6 y ya no lanzó error. gracias :)
