### ISSUE TITLE
[Tarea] Respecto a los argumentos para crear las clases

### ISSUE THREAD

**Issue by dfloreaa** [IIC2143-2021-1/Syllabus#40]
Si bien en el enunciado se dice que la modelación es sugerida, luego dice que debe contener todas las clases descritas. Eso incluye los atributos que se deben entregar para poder instanciarlas? O puedo quitar algunos?

Gracias de antemano ☺

**Comment by CmPoblete** [comment]
Puedes agregar o quitar los atributos y métodos que quieras mientras que crees las 4 clases.
La modelación que sale en el enunciado es una ayuda solamente
