### ISSUE TITLE
[Tarea] Métodos de punto 7 que reciban parámetros 

### ISSUE THREAD

**Issue by denisseleiva** [IIC2143-2021-1/Syllabus#41]
Holaa! Quería preguntar si puedo incluir parámetros en los métodos pedidos del punto 7 (por ejemplo la instancia de la clase Liga) para no hacer uso de variables globales. ¿Se puede?

Graciass!

**Comment by CmPoblete** [comment]
Hola, si puedes incluir parametros. Aunque igual podrias incluirlos como metodos de alguna clase para poder tener los atributos, pero es decisión tuya

**Comment by denisseleiva** [comment]
okaa, gracias!
