### ISSUE TITLE
[Tarea] Pasar de diccionario a objeto

### ISSUE THREAD

**Issue by MagyarSplit** [IIC2143-2021-1/Syllabus#42]
Hola. Me surgió la duda de cómo pasar un diccionario (como el de abajo), a inicializar un objeto que tiene como atributos a todas los relaciones llave-valor del diccionario, en una sola linea de código (o la menor cantidad de código, es decir, evitar escribir cada atributo por separado lo cual es tedioso y toma varias lineas). Yo hacia esto en python siempre, pero ahora no encuentro ningún comando que no me tire error. Muchas gracias

`#trainers[0] = {"id"=>"1", "nombre"=>"Moises", "pokemon1"=>"64", `
`# "pokemon2"=>"70", "pokemon3"=>"56", "pokemon4"=>"81", "pokemon5"=>"123", "pokemon6"=>"19"}`
 
`class Trainer`
`def initialize(data)`
` # aquí falta la linea de código `
`end`
`end`

`print Trainer.new(trainers[0]).id`

**Comment by CmPoblete** [comment]
Hola, quizas esto pueda servirte [https://stackoverflow.com/questions/1572660/is-there-a-way-to-initialize-an-object-through-a-hash](https://stackoverflow.com/questions/1572660/is-there-a-way-to-initialize-an-object-through-a-hash)

**Comment by MagyarSplit** [comment]
Muchas gracias! Solucionado
