### ISSUE TITLE
[Tarea] Duda archivo output

### ISSUE THREAD

**Issue by sebacarrasco** [IIC2143-2021-1/Syllabus#43]
Hola, en la parte de mostrar todos los entrenadores de la liga ¿se debe poner a los pokemones ordenados por id? lo pregunto porque creo que en el archivo de output que subieron está así pero por como está en el enunciado yo había entendido que se ponían en el mismo orden que en el que venían en el csv.
Si es el caso de que hay que ponerlos ordenados por id, ese orden también debe usarse para los combates? (creo que tampoco salía en el enunciado)

**Comment by CmPoblete** [comment]
Es por el orden que sale en el csv, a mi se me paso y los ordene por id por equivocacion. Lo arreglare

**Comment by CmPoblete** [comment]
Arreglado

**Comment by sebacarrasco** [comment]
Gracias!

**Comment by CmPoblete** [comment]
gracias a ti por darte cuenta
