### ISSUE TITLE
[Paso 8 - Windows] - error occurred while installing pg (1.2.3)

### ISSUE THREAD

**Issue by imant1** [IIC2143-2021-1/Syllabus#45]
Hola, tuve problemas con la instalación de WSL y ubuntu, por lo que estaba haciendo todo el procesos de nuevo y al correr `rails new my_app --database=postgresql` me tiró este error:

![image](https://user-images.githubusercontent.com/64439029/113308900-0426a000-92dd-11eb-9e54-a48e074beafa.png)

Y después, al correr `bundle install` me tiró el siguiente error:

![image](https://user-images.githubusercontent.com/64439029/113308978-16084300-92dd-11eb-8857-0b0a7b081a5a.png)

Corrí el comando que sale arriba en rojo (`gem install pg -v ...`) y me tiró lo siguiente:

![image](https://user-images.githubusercontent.com/64439029/113309302-64b5dd00-92dd-11eb-9df2-96a59a5e4747.png)

Traté de seguir igual con el proceso, pero como el `bundle install` no pudo terminar no se crearon las carpetas necesarias en mi carpeta raíz de proyecto `my_app`

**Comment by felipefuentesporras** [comment]
Creo que es un problema con el uid al tenerlo default root en vez de como el tuyo.  Te dejo estos links donde explican el error y como cambiarlo:
https://stackoverflow.com/questions/25514553/cannot-create-a-new-rails-project-due-to-chmod
https://serverfault.com/questions/39288/how-to-change-owner-of-mount-point

**Comment by benjaguiloff** [comment]
Hola! Tuve un error muy similar. A mi me arroja lo siguiente al hacer `rails new proyecto_nuevo --database=postgresql`

![Captura de pantalla (116)](https://user-images.githubusercontent.com/48481681/113417579-1286c180-939a-11eb-98df-7ab7d44a5cbd.png)

![Captura de pantalla (117)](https://user-images.githubusercontent.com/48481681/113417677-54176c80-939a-11eb-920f-ed3405663f54.png)

¿Pudiste averiguar como se soluciona?

**Comment by imant1** [comment]
Hola @benjaguiloff, todavía no he solucionado el problema, mi ayudante de proyecto está cachando con los otros ayudantes qué se puede hacer para solucionarlo.

**Comment by meretamal** [comment]
@ignaciomansuy @benjaguiloff, pueden asegurarse de haber instalado postgres correctamente usando todos los comandos de la guía de instalación?

Al correr `sudo apt-get install postgresql postgresql-contrib libpq-dev` se debería instalar postgres y las dependencias de desarrollador que necesita, con lo que se evita ese mismo error.

**Comment by imant1** [comment]
@meretamal @benjaguiloff @felipefuentesporras  resolví el problema. Lo que pasaba era que estaba creando el proyecto en los "archivos de Windows", en mi caso estaba en  `/mnt/c/Users/ignac/...`, lo que hice fue ir a `/home/ignac` y en ese directorio correr el `rails new my_app --database=postgresql`.
Para el próximo semestre quizás pueden explicitar en la guía del setup que el proyecto se debe crear en los "archivos del sistema de Linux"

**Comment by benjaguiloff** [comment]
Yo también lo pude solucionar, pero con lo que dijo @meretamal. Corrí `sudo apt-get install postgresql postgresql-contrib libpq-dev` en vez de `sudo apt-get install postgresql postgresql-contrib` en el paso 4, y no me volvieron a salir los errores.
