### ISSUE TITLE
[Tarea] Consulta resultado del output

### ISSUE THREAD

**Issue by data-diego** [IIC2143-2021-1/Syllabus#47]
Hola, el output debe exactamente el mismo al de ejemplo?

revisé infinitas veces y mi top 5 no cambia de
{3,Jerry,45}
{5,Cristobal,40}
{4,Jose Antonio,31}
{2,Ignacio,30}
{6,Catalina,30}

**Comment by CmPoblete** [comment]
Hola, el archivo output.txt es el output esperado para el ejemplo. Yo también revise un buen rato la solución para encontrar algún error, pero no encontré error en la lógica según lo que se pide en el enunciado. Podrías ir imprimiendo lo que pasa cada turno de los combates para ver si hay algún error.

**Comment by data-diego** [comment]
![image](https://user-images.githubusercontent.com/28828655/113360140-9354a780-931f-11eb-9c68-b60f74c81ede.png)

Gracias
