### ISSUE TITLE
Orden Top pokemones

### ISSUE THREAD

**Issue by domingo2000** [IIC2143-2021-1/Syllabus#48]
Hola, tengo una duda, para los top_pokemones, no me queda claro si es que un entrenador tiene por ejemplo un charizard, y otro tambien tiene un charizar, ¿son contabilizados de manera distinta o como si fuera un solo pokemon para el top pokemones?, es decir, se ve cual es la "raza" de pokemon mas top, o se ve literalmente que instancia de pokemon es el mejor (puesto que el charizard de un entrenador no es el mismo charizard de otro entrenador)

**Comment by jmndoza** [comment]
Hola @domingo2000, revisa #35

**Comment by domingo2000** [comment]
Gracias!
