### ISSUE TITLE
Problema de Setup

### ISSUE THREAD

**Issue by jtmeyer98** [IIC2143-2021-1/Syllabus#49]
Estoy en el paso 3 de la guía de setup y al correr el código:

joset@LAPTOP-HJN2RR2R:~$ rvm -v

me aparece lo siguiente:

Command 'rvm' not found, but there are 19 similar ones.

![image](https://user-images.githubusercontent.com/37156969/113423614-30a5ef00-93a5-11eb-8522-cc3ba0f1e0f7.png)

**Comment by matumartinez** [comment]
Hola!

Quizás no se te instaló bien rvm. Prueba con lo siguiente:

`
rm -rf .rvm
`

Y posteriormente instala de nuevo rvm. Me avisas si te funcionó.

**Comment by jtmeyer98** [comment]
Si me funcionó!!! muchas gracias (:
