### ISSUE TITLE
Error de instalación de Ubuntu (Error: 0x80370102)

### ISSUE THREAD

**Issue by benjaguiloff** [IIC2143-2021-1/Syllabus#5]
Hola! Después de descargar WSL traté de instalar Ubuntu, pero al abrir la consola me arroja el siguiente error:

`WslRegisterDistribution failed with error: 0x80370102`
`Error: 0x80370102 No se pudo iniciar la mßquina virtual porque no se instal¾ una caracterÝstica requerida.`

Cabe destacar que estoy instalando la versión 20.04 de Ubuntu.

**Comment by meretamal** [comment]
Hola :grin: 

Es probable que tengas que activar la virtualización directamente desde la BIOS :upside_down_face:.

Si quieres podemos coordinar una llamada para ayudarte a hacerlo.

**Comment by vichoruiz** [comment]
hola, llevo días con este problema jaja, podría coordinar una llamada también?
