### ISSUE TITLE
No puedo ejecutar archivo ruby

### ISSUE THREAD

**Issue by En-clases** [IIC2143-2021-1/Syllabus#50]
Hola, he intentado correr mi archivo ```Tarea.rb``` con cmd y Powershell de Windows pero ambos me arrojan el mismo error: 
![image](https://user-images.githubusercontent.com/69520590/113423846-94301c80-93a5-11eb-9a10-98b9a70b37a8.png)
Quizás es importante mencionar que sólo llegué hasta el paso 6 de la guía de instalación para Windows ya que dijeron que no todos los integrantes del grupo debían crear el proyecto.
Espero me puedan ayudar, gracias.

**Comment by meretamal** [comment]
Hola 😁

Si es que seguiste la guía de instalación, entonces debes estar usando WSL. Para correr tanto tu proyecto como archivos de ruby (para la tarea por ejemplo), usa el terminal de Ubuntu que instalaste.

**Comment by En-clases** [comment]
Muchas gracias! Pensé que había visto en al ayudantía que abrían los archivos ruby con la powershell.

**Comment by CmPoblete** [comment]
En la ayudantia de ruby corri las cosas en la powershell porque tenia instalado ruby en windows
