### ISSUE TITLE
FATAL: role "*" does not exist

### ISSUE THREAD

**Issue by amunitac** [IIC2143-2021-1/Syllabus#52]
Hola, me aparece eso al entrar al link, nose porque pueda ser, segui todos los pasos.
![image](https://user-images.githubusercontent.com/62104845/113456375-839e9700-93e3-11eb-8d7a-b632c2866643.png)
![image](https://user-images.githubusercontent.com/62104845/113456446-af218180-93e3-11eb-9741-b7ebd6e47f9a.png)

**Comment by matumartinez** [comment]
Hola!

El usuario que creaste tiene rol de superuser?

**Comment by meretamal** [comment]
Hola 😁

A parte de lo que mencionó @matumartinez, puedes asegurarte de haber creado un `superuser` con ese nombre?

**Comment by amunitac** [comment]
hola
segun yo si quedo el superuser con ese nombre, segui todos los pasos y siempre ponia ese mismo nombra.
Como podria revisar si efectivamente quedo como superuser?

**Comment by matumartinez** [comment]
Tienes que iniciar postgres y después entrar con:

`
psql postgres
`

Una vez dentro:

`
\du
`

Ahí veras si tu usuario es superuser

**Comment by amunitac** [comment]
hola, ahi pude volver mi usuario superuser y funciono perfecto
Gracias!
