### ISSUE TITLE
[Ayudantia 1] Problema Require

### ISSUE THREAD

**Issue by mmrodriguez5** [IIC2143-2021-1/Syllabus#53]
Hola! 
Puse la siguiente linea para instalar la gema HTTParty.

gem install "httparty"

Me tiro el siguiente error:

Traceback (most recent call last):
ay1_3.rb:7:in `<main>': undefined method `install' for main:Object (NoMethodError)

Cómo lo puedo arreglar?

**Comment by CmPoblete** [comment]
Hola, estás ejecutando gem install desde la consola o desde el código?

**Comment by jerrymendoza** [comment]
Hola @mmrodriguez5 ! 
probaste sin las comillas , solo `gem install httparty`  ?

**Comment by mmrodriguez5** [comment]
desde la consola

**Comment by CmPoblete** [comment]
Si ejecutas ruby -v te dice la versión se ruby?

**Comment by mmrodriguez5** [comment]
Me dijo esto

ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

**Comment by CmPoblete** [comment]
Me podrias mandar un apntallazo de lo que sale en la consola al hacer gem install y del archivo ay1_3.rb (que sale que hay un error en la linea 7)

**Comment by mmrodriguez5** [comment]
![Captura](https://user-images.githubusercontent.com/53843313/113494019-00e90b00-94bb-11eb-8fbf-43064b03eb13.PNG)

![c1](https://user-images.githubusercontent.com/53843313/113494039-283fd800-94bb-11eb-95e4-020379c9a521.PNG)

**Comment by CmPoblete** [comment]
Hola, el problema es que gem install httparty lo tienes que ejecutar desde la consola. Eso no debe ir en el código.

**Comment by mmrodriguez5** [comment]
Muchas gracias!
