### ISSUE TITLE
Formato de entrega de Tarea 1

### ISSUE THREAD

**Issue by En-clases** [IIC2143-2021-1/Syllabus#54]
Hola, no sé si debo subir la carpeta ```data``` con el resto de archivos ```.rb``` para la tarea ya que solo especifican que no debemos subir los archivos ```.csv```. Debemos entonces subir la carpeta ```data``` vacía?

**Comment by CmPoblete** [comment]
Hola, sube solo los archivos .rb

**Comment by En-clases** [comment]
Ok, gracias!
