### ISSUE TITLE
Como eliminar un proyecto creado

### ISSUE THREAD

**Issue by Gustav2000** [IIC2143-2021-1/Syllabus#55]
Hola, quería saber cuál es el comando para eliminar un proyecto creado anteriormente a modo de práctica (paso 8)?

Muchas gracias.

**Comment by matumartinez** [comment]
Hola!

No sé si entendí bien tu pregunta, quieres eliminar el proyecto de rails o la base de datos?

**Comment by Gustav2000** [comment]
Osea tengo 2 opciones:
1. Eliminar un proyecto de rails (no la base de datos) y crear una nuevo en la carpeta en la que necesito en la que esté
2. o mover el proyecto desde donde lo cree hasta la carpeta que lo necesito (el repo).

Ya que no me manejo mucho con wsl y cuando entro a esta consola no se en que parte "física" del computador estoy situado.

**Comment by meretamal** [comment]
Si es que estás usando wsl, puedes borrarlo ejecutando `rm -rf nombre-de-tu-carpeta` (esto lo puedes usar para carpetas no vacías. Si es que quieres borrar una carpeta vacía puedes correr `rmdir nombre-de-tu-carpeta`).

Si es que quieres mover todo el contenido de una carpeta a otra, puedes correr `mv carpeta-1/* carpeta-2`

Si es que quieres crear un proyecto nuevo dentro de una carpeta ya existente, puedes correr `rails new . --database=postgresql`

Ojo que esto funciona si estás en el directorio que contenga a estas carpetas, sino tienes que escribir el path (relativo por ejemplo) a ellas.

**Comment by CmPoblete** [comment]
si quieres llegar hasta algun punto conocido, haz 'cd /mnt/c' (sin las comillas) y deberias quedar en el disco c, si no te encuentra el directorio muevete con 'cd ..' (sin comillas) hasta llegar a la carpeta c o mnt (y ahi te mueves al disco c)

**Comment by Gustav2000** [comment]
Muchas gracias!
