### ISSUE TITLE
Paso 5: psql: error: FATAL:  password authentication failed for user "Mac"

### ISSUE THREAD

**Issue by Sweinzierl28** [IIC2143-2021-1/Syllabus#57]
En el paso 5 de la instalación en Mac, logré correr el primer comando que nos pusieron para iniciar postgres, pero después cuando ingreso el segundo comando para ingresar a la consola, me pide inmediatamente la contraseña para el usuario "Mac". Es como si al instalarlo se hubiera creado automaticamente una cuenta con el nombre de mi computador, pero claramente nose a cual contraseña se refiere, ya que intenté con la misma de mi computador y no funciona. 
Sin esta contraseña no me deja crearme otro usuario, ni entrar a postgres. Les dejo el resumen de lo que me aparece:

Macs-MacBook-Pro-2:~ Mac$ brew services start postgresql
Service `postgresql` already started, use `brew services restart postgresql` to restart.
Macs-MacBook-Pro-2:~ Mac$ psql postgres
Password for user Mac: 
psql: error: FATAL:  password authentication failed for user "Mac"
Macs-MacBook-Pro-2:~ Mac$ CREATE USER SWeinzierl28 WITH SUPERUSER PASSWORD 'xxx';
-bash: CREATE: command not found
Macs-MacBook-Pro-2:~ Mac$

**Comment by matumartinez** [comment]
Hola!

Esa contraseña que te pide es la de tu macbook, la debes estar ingresando mal.

**Comment by Sweinzierl28** [comment]
No lo es! He intentado muchas veces y no funciona

**Comment by Sweinzierl28** [comment]
Intenté creandome una cuenta (sweinzierl28) mediante la página web de postgres y luego si ingreso:
psql postgres -U sweinzierl28
e ingreso mi contraseña (recién creada y modificada) y me sigue apareciendo: 
psql: error: FATAL: password authentication failed for user "sweinzierl28"

Intenté borrando y reinstalando postgres, cambiando la constraseña de mi computador, de mi usuario de postgres y nada me funciona.

También intenté lo siguiente que encontré en internet pero me tira de todas formas error:
Macs-MacBook-Pro-2:~ Mac$ brew services restart postgresql
Stopping `postgresql`... (might take a while)
==> Successfully stopped `postgresql` (label: homebrew.mxcl.postgresql)
==> Successfully started `postgresql` (label: homebrew.mxcl.postgresql)
Macs-MacBook-Pro-2:~ Mac$ pg_ctl -D /usr/local/var/postgres status
pg_ctl: no server running
Macs-MacBook-Pro-2:~ Mac$  pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
waiting for server to start.... stopped waiting
pg_ctl: could not start server
Examine the log output.

**Comment by matumartinez** [comment]
Prueba con esto:
`
 sudo -u postgres psql -c "ALTER USER <tu usuario> PASSWORD 'postgres';"
`
Después de eso intenta acceder usando la contraseña "postgres".
Si no, mira este link:

https://stackoverflow.com/questions/7695962/postgresql-password-authentication-failed-for-user-postgres

**Comment by Sweinzierl28** [comment]
No me funcionó la contraseña "postgres" y entrando al link que me dijiste probé con:
sudo -u postgres psql       
y también con:
sudo -u postgres template1
y ninguna me funcionó. Luego dice que verifique el archivo /etc/postgresql/8.4/main/pg_hba.conf pero nose dónde buscar eso, ya que si lo copio en mi terminal me aparece que no existe.

**Comment by Sweinzierl28** [comment]
Lo logré solucionar!!
Con la info de este link:
https://stackoverflow.com/questions/54407256/postgresql-unable-to-login-to-postgres-admin-user-and-setting-auth-to-trust-didn
