### ISSUE TITLE
[Tarea Ruby] Duda orden pokemones CSV

### ISSUE THREAD

**Issue by SebaHagedorn** [IIC2143-2021-1/Syllabus#59]
Hola!
Al comparar el ejemplo del output me doy cuenta que los pokemones para cada entrenador están ordenados en un orden diferente al del csv. A qué se debe esto? No se si me estoy saltando algo del enunciado :disappointed:.

Gracias!

**Comment by CmPoblete** [comment]
Hola, hace unos días arregle ese problema. Antes me había equivocado y los estaba ordenando por id, pero alguien me avisó y arregle ese error. Si deben estar según como salen en el csv

**Comment by SebaHagedorn** [comment]
Me acabo de dar cuenta que cambiaron el output esperado :facepalm:. Gracias igual!
