### ISSUE TITLE
Error paso 8: No such file or directory

### ISSUE THREAD

**Issue by sreitze** [IIC2143-2021-1/Syllabus#6]
![image](https://user-images.githubusercontent.com/69603335/112329480-feeea300-8c95-11eb-9b2f-7a5b89d269aa.png)

No logro avanzar al siguiente comando. Todo lo anterior la resultó bien, pero al llegar a este paso, me dice lo que esta en la foto. Gracias

**Comment by crvargasu** [comment]
Hola!
La idea es que en `<nombre proyecto>`, pongas un nombre para identificar esta carpeta.

Por ejemplo, le puedes colocar el nombre de `app`. En ese caso el comando sería.

`rails new app --database-postgresql`

**Comment by Huasito-Appel** [comment]
no soy ayudante, pero cuando generes tu proyecto en el paso 7, NO uses <>, ponle un nombre nomas como first_project

**Comment by sreitze** [comment]
okaa muchas gracias.
