### ISSUE TITLE
Pregunta con Gitflow

### ISSUE THREAD

**Issue by dchahuan** [IIC2143-2021-1/Syllabus#60]
Para la entrega 0 es necesario el uso de gitflow??

**Comment by meretamal** [comment]
Hola 😁 

Si, pero no de una manera completa. Como mínimo se necesita que tengan dos ramas principales, por ejemplo `main` y `development` y que desde `development` saquen _feature branches_. La idea es pasen los cambios de una rama a otra a través de _merges_ (ya sea usando _pull requests_ o no) y que todo lo que pase a `main` esté en producción (en Heroku)
