### ISSUE TITLE
[Tarea] Duda con puntajes finales de los entrenadores

### ISSUE THREAD

**Issue by crow-rojas** [IIC2143-2021-1/Syllabus#62]
Hola!

Llevo cabeceandome toda la tarde un problema que tengo. Logré ya hacer todos los combates pero al ver los puntajes finales de los entrenadores me fijé que me dan todos distintos a como sale en el output que pusieron. El único que me sale igual es Moises, de hecho, los imprimí en consola y esto obtengo:

Moises tiene 17 puntos!
Ignacio tiene 33 puntos!
Jerry tiene 41 puntos!
Jose Antonio tiene 28 puntos!
Cristobal tiene 39 puntos!
Catalina tiene 36 puntos!

mientras que el output los puntos son 17, 30, 45, 26, 40, 34, respectivamente. He revisado todo, la fórmula del daño el orden de los turnos, lo de la velocidad, y se ve todo bien, he hecho prints por todas partes y aún no encuentro mi error D: Alguna idea? :( muchas gracias

**Comment by IgnaciaJ** [comment]
jajaja me sumo a esta pregunta mi output me da que los puntajes son 17, 30, 45, 31, 40 y 30

**Comment by crow-rojas** [comment]
@IgnaciaJ ,@jerrymendoza me ayudó testeando cosas y era porque en algunos combates los dos pokemones que se enfrentaban eran el mismo objeto, así que el pokemon se hacía daño a si mismo. Revisa si puede ser eso!

@jerrymendoza gracias crack :D

**Comment by IgnaciaJ** [comment]
@crow-rojas buenaa gracias voy a revisar!!

**Comment by crow-rojas** [comment]
@IgnaciaJ logré coincidir dos puntajas nomas jajaja :( más rato seguiré intentando

**Comment by IgnaciaJ** [comment]
@crow-rojas a mi me sigue sin calzar catalina y jose antonio jajajaj

**Comment by IgnaciaJ** [comment]
@crow-rojas pude calzar los nombres!! tu?

**Comment by crow-rojas** [comment]
@IgnaciaJ aún no, de hecho estoy haciendo todo el código de nuevo jajaja qué te fallaba?

**Comment by IgnaciaJ** [comment]
@crow-rojas tenia un error como con la vida_actual y la máxima del pokemon al momento de restarle el ptje(al final cree una variable auxiliar con la vida del pokemon para que no me pasara lo de los pokemons repetidos)

**Comment by crow-rojas** [comment]
@IgnaciaJ sigo sin poder resolverlo :/ como hiciste para el daño? lo hiciste tal cual con ints como sale en el enunciado o usaste floats?

**Comment by IgnaciaJ** [comment]
@crow-rojas use ints!

**Comment by CmPoblete** [comment]
no deberia afectar mucho el uso de int o float

**Comment by icontreras2** [comment]
@IgnaciaJ, aún tienes estos puntajes: 17, 30, 45, 31, 40 y 30? tengo exactamente los mismos y estoy en busca del error que me hace diferir de los puntajes dados por el "output ejemplo"

**Comment by IgnaciaJ** [comment]
@icontreras2 holaa!! Lo pude arreglar, tenía un problema sobre como estaba definiendo la vida del pokemon, que antes editaba la vida actual de cada pokemon(y nose porque a veces se me bajaban solas las vidas), asi que hice una variable que partía con la vida máxima del pokemon que estaba atacando y a esta se le iba restando cuando lo atacaban. Asi me funciono bien :)

**Comment by icontreras2** [comment]
@IgnaciaJ hola!!! voy a ver cómo me funciona eso muchas gracias!!!
