### ISSUE TITLE
Error set-up paso 10:  Operation not permitted - bs_fetch:atomic_write_cache_file:chmod (Errno::EPERM)

### ISSUE THREAD

**Issue by Emiliax16** [IIC2143-2021-1/Syllabus#64]
Hola, revisé las otras issues con el error en el paso 10 y ninguna me funcionó. Seguí los pasos de la ayudantía y en ningún momento me resultó el crear la base de datos. Tenía instalado el ubuntu 16 y lo desintalé e instalé el 20. También eliminé los proyectos creados y volví a repetir los pasos pero no hay caso. He intentado de todo :c Les dejo un screenshot del problema!
![error](https://user-images.githubusercontent.com/69869381/113793135-97b10400-9715-11eb-9c5b-da2d253b7d11.jpg)

**Comment by meretamal** [comment]
Hola 😁 

Puedes ejecutar `sudo rm -rf tmp` (desde el directorio de tu proyecto) y luego seguir con el _setup_?

**Comment by Emiliax16** [comment]
Lo acabo de hacer pero continuo con el mismo error 😭

**Comment by meretamal** [comment]
Hola, según lo que vi, estás abriendo Ubuntu desde las carpetas de Windows. Me imagino que es porque estás usando windows terminal.

Podrías intentar crear un nuevo proyecto abriendo directamente Ubuntu para que se abra desde los nuevos directorios que te crea para emular tu ambiente de linux (abre la app de ubuntu que instalaste y haz el _steup_)?

Si eso funciona, después puedo mostrarte como hacer que, abriéndolo desde windows terminal, tu directorio incial sea ese.

**Comment by Emiliax16** [comment]
Cuando llegué  a la parte de crear un nuevo proyecto, no me crea todas las carpetas y me sale este error:
![error_setup](https://user-images.githubusercontent.com/69869381/113794683-19eef780-9719-11eb-9a76-a9c1e99b8084.jpg)

**Comment by meretamal** [comment]
Por algún motivo tu terminal sigue partiendo desde tus carpetas de Windows, en las cuales no vas a tener todos los permisos para hacer el _setup_.

Corre
```bash
cd ~
nano .bashrc
```

Al principio del archivo escribe `cd ~`
Luego presiona:
* **CTRL + X**
* **y**
* **ENTER**

Luego reincia tu terminal y vuelve a intentar el _setup_.

**Comment by Emiliax16** [comment]
Se creó bien la carpeta con el nombre del proyecto!!. ¿Cómo lo abro en sublime text? porque no sé cual es la ruta del archivo.
![ruta](https://user-images.githubusercontent.com/69869381/113798277-e1531c00-9720-11eb-98b4-5fe93d099944.png)

**Comment by meretamal** [comment]
Estando en el directorio de tu proyecto, intenta correr `subl .`
