### ISSUE TITLE
Pregunta con respecto a paths a carpetas

### ISSUE THREAD

**Issue by Gustav2000** [IIC2143-2021-1/Syllabus#65]
Hola, quería saber si para la tarea está bien que escribamos un path para leer los archivos con extensión .csv de la siguiente forma:  'data\entrenadores.csv'.  Mi pregunta es si importa la forma en que pongamos el path ('\\' ó '/')?, ya que en python uno podía usar la librería **os** con su método path.join() el cual se encargaba de unir el path de forma correcta dependiendo el sistema operativo del computador con el que se estuviera corriendo el código.

**Comment by CmPoblete** [comment]
No se preocupen por eso

**Comment by Gustav2000** [comment]
Oka, muchas gracias.
