### ISSUE TITLE
problema con Git add de proyecto

### ISSUE THREAD

**Issue by Juampisaez** [IIC2143-2021-1/Syllabus#66]
Hola, estaba tratando de hacer el git add del proyecto, pero al intentarlo me lanza este error:
![image](https://user-images.githubusercontent.com/48323752/113807113-8a097780-9731-11eb-9bb8-bdc9e3c998e1.png)
tambien probe haciendo `git add Proyecto37/`

Si alguien pudiera orientarme, se lo agradeceria.
Gracias!

**Comment by CmPoblete** [comment]
Hola, específicamente que es lo que quieres hacer?

**Comment by Juampisaez** [comment]
Subir el proyecto, nada mas

**Comment by CmPoblete** [comment]
Creaste el repo?

**Comment by Juampisaez** [comment]
Sii, es la repo que dieron para el proyecto
Por ahi vi que rails crea en el proyecto una carpeta .git que hay que borrar, es asi?

**Comment by CmPoblete** [comment]
Proyecto37/ está dentro de la carpeta del repositorio o no?

**Comment by Juampisaez** [comment]
Sii, esta dentro

**Comment by CmPoblete** [comment]
Escríbeme a mi mail cmpoblete@uc.cl y vemos que está pasando

**Comment by jmndoza** [comment]
@Juampisaez la carpeta /Proyecto37 tiene un repo iniciado ? (un .git ?)

**Comment by Juampisaez** [comment]
sii, tiene una carpeta .git dentro de /Proyecto37

**Comment by jmndoza** [comment]
@Juampisaez es posible que tengas un repo dentro de otro repo?

**Comment by Juampisaez** [comment]
Como? lo unico que hice fue crear en proyecto con rails en la repo que se nos dio. 
Puede ser que borrando el .git del proyecto de rails, se solucione?

**Comment by jmndoza** [comment]
@Juampisaez cuando creas el proyecto con Rails te incluye en git (hace el git init por ti), entonces esta reclamando que hay un repo dentro de otro (un submodulo), intenta borrando el .git que esta adentro de proyecto37

**Comment by jmndoza** [comment]
@Juampisaez igual te recomiendo que dejes los archivos dentro del repo y no dentro de una subcarpeta... hint: `rails new .`

**Comment by Juampisaez** [comment]
Oka, gracias!
