### ISSUE TITLE
[Tarea] Duda top_pokemones

### ISSUE THREAD

**Issue by IgnacioPorte** [IIC2143-2021-1/Syllabus#67]
Hola, me entró la duda en el método top_pokemones. Qué cuenta como combate sobrevivido,  asumo que es cuando un entrenador gana un combate y no cada enfrentamiento que sobrevive peleando con otro pokemon.

**Comment by CmPoblete** [comment]
Es cuando gana un combate. Todos los pokemones que sigan con vida cuando el entrenador gana el combate, cuenta como 1 combate sobrevivido para cada uno

**Comment by IgnacioPorte** [comment]
Vale, gracias.
