### ISSUE TITLE
Push de databse a github

### ISSUE THREAD

**Issue by domingo2000** [IIC2143-2021-1/Syllabus#68]
Hola, trabajando localmente con rails me surge una duda, si yo monto un proyecto de rails localmente, la base de datos se va llenando localmente, pero cuando pusheo el proyecto a github y lo clono desde otro computador, al volver a correr el proyecto en localhost resulta que se han borrado tanto las migraciones hechas a la base de datos, como las instancias que se han creado usando la pagina web anteriormente (de manera local en otro PC). Entonces mi duda es, como puedo mantener los datos de la base de datos iguales en distintos computadores usando github??

**Comment by crvargasu** [comment]
Hola! Más adelante se les enseñará la implementación de seed, que es justamente para poder programar datos de manera de poder cargarlos en distintas BD al ejecutar el comando `rails db:seed`

Ahora, las migraciones son otra cosa, estas se van guardando en la carpeta` db/migrate/`, y puedes correrlas en otros computadores simplemente con `rails db:migrate`
