### ISSUE TITLE
ERROR al ejecutar comando "gem install rails -v 5.2.4" (Mac)

### ISSUE THREAD

**Issue by juanluis2019** [IIC2143-2021-1/Syllabus#69]
Al ejecutar en la terminal "gem install rails -v 5.2.4" me sale el siguiente ERROR

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.

Que hago?

**Comment by jmndoza** [comment]
@juanluis2019 Intentaste sudo gem install rails -v 5.2.4 ?

**Comment by juanluis2019** [comment]
@jerrymendoza Lo acabo de correr, me arroja el siguiente error:
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

**Comment by cristobalgon** [comment]
Hola! pudiste solucionarlo?? Tengo el mismo error.

**Comment by cristobalgon** [comment]
Pude encontrar una solución al respecto! Se las comento a continuación:

Lo que a mi me funcionó, lo hice de la siguiente manera... deben ejecutarlos cómo salen:

1 - brew install shared-mime-info
2 - gem install bundler:1.17.3
3 - gem update --system

Luego desintalé el bundler 2.2.16 que tenía con el comando
3.1 - gem uninstall bundler
y seleccioné la opción de desinstalar el de 2.2.16 y quedarme con el 1.17.3 (no sé si funciona con el 2.2.16...)

4 - bundle update --conservative mimemagic

Finalmente, me funciona correr 'rails s'!!!

Espero que te haya servido!
