### ISSUE TITLE
Error paso 2: gpg recepción del servidor de claves fallida

### ISSUE THREAD

**Issue by franancic** [IIC2143-2021-1/Syllabus#7]
Hola! al realizar el segundo comando gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB me aparece el error "gpg: recepción del servidor de claves fallida: Server indicated a failure", lo que me ha impedido de poder seguir el manual de instalación (Mac) :(

**Comment by matumartinez** [comment]
En el terminal:

`
sudo vi /etc/resolv.conf
`

Ahí entrarás al editor de texto del terminal (vi). Apreta la tecla "i", al final de ese archivo agrega "nameserver 8.8.8.8" y apreta la tecla "esc" para salir del modo escritura. Posteriormente escribe ":wq!" y apreta la tecla enter. Después de eso vuelve a intentar lo de las llaves y debería funcionar.
