### ISSUE TITLE
Insights git para ver branches

### ISSUE THREAD

**Issue by domingo2000** [IIC2143-2021-1/Syllabus#71]
Hola, tenía una duda, resulta que quiero meterme a github y  ver en insight mis branches commits, y otras cosas del proyecto, pero resulta que cuando voy a insights, me dice que contacte con el administrador para activar esa "feature" en github. Pueden ustedes activar eso para la carpeta del proyecto?

**Comment by meretamal** [comment]
Hola, por la licencia que tenemos en la org, no es posible darles acceso a esa _feature_ sobre sus repos.
