### ISSUE TITLE
Configuración LineLength Rubocop 

### ISSUE THREAD

**Issue by Mamunoz42** [IIC2143-2021-1/Syllabus#72]
Holaaa!! 😸 

Cuando estaba realizando la configuración `RUBOCOP` para mi proyecto decidimos que el `LineLength` seria 100, sin embargo dentro del directorio `config` existen ficheros los cuales tienen más de 100 columnas, seria legal que yo dentro de la configuración del `LineLength` excluya este directorio, ya que por defecto se crea con esa cantidad de columnas. Y esta pregunta igual va dirigida a esos archivos que por defecto rompan nuestra configuración de `RUBOCOP`.

De antemano muchas gracias 👍🏽

**Comment by YehudaGurovich** [comment]
Tenemos la misma duda! Lograron resolverlo?

**Comment by CmPoblete** [comment]
Hola, esas cosas hablenlas con su product owner para llegar un acuerdo.
