### ISSUE TITLE
[TAREA] Caso en que se enfrentan pokemones con el mismo id entre sí

### ISSUE THREAD

**Issue by icontreras2** [IIC2143-2021-1/Syllabus#74]
Hola!!! Noté que en un caso se enfrentan pokemones con el mismo id entre sí, lo que significa que hay un pokemon peleando contra sí mismo. Para efectos del programa, ¿cómo proceder en dichos casos? Opción 1, dado que en este caso el pokemon que se autodestruye (como ambos pokemones tienen igual id, ambos quedarían eliminados pues cuando uno queda con vida menor que 0, automáticamente el otro también quedará con esa vida), ¿se eliminaría tanto el pokemon de un entrenador como el pokemon del otro entrenador? Opción 2, o bien podemos dejar vivo al último pokemon que atacó (actualizando su vida en función de su vida máxima y las veces que fue atacado por el pokemon del entrenador rival que resultó eliminado). Opción 3, proceder de otra forma diferente a las mencionadas. 

El saber cómo proceder en dichos casos me interesa más que nada para poder dar con el output esperado.  Muchas gracias :)

**Comment by CmPoblete** [comment]
No se elimina, puedes considerarlos como instancias distintas. Si el pokemon 1 se enfrenta contra el pokemon 1, son 2 pokemones distintos, solo que poseen las mismas estadisticas

**Comment by icontreras2** [comment]
perfecto, muchas gracias!
