### ISSUE TITLE
Permisos Heroku

### ISSUE THREAD

**Issue by miguel-mrtnez** [IIC2143-2021-1/Syllabus#75]
Hola, al momento de intentar conectar una pipeline de **Heroku** al repositorio de **GitHub**, me deniega el acceso con este mensaje:

![image](https://user-images.githubusercontent.com/58334917/114320590-8df81980-9ae4-11eb-8a60-52b66ddbf802.png)

Agradecería cualquier ayuda, gracias.

**Comment by meretamal** [comment]
Hola 😁 , probablemente es por los permisos que tienen en sus repos.

Por favor usen `Heorku CLI` para hacer el _deploy_, ya que no les daremos permisos de admin sobre sus repositorios.

**Comment by miguel-mrtnez** [comment]
Muchas gracias!
