### ISSUE TITLE
[Tarea] Duda calculo vida actual

### ISSUE THREAD

**Issue by amyaranta** [IIC2143-2021-1/Syllabus#77]
Hola, al dividir la defensa por 4, el número que obtengo debe ser int o float?
Muchas gracias de antemano :).

**Comment by CmPoblete** [comment]
Hola, la solución contempla ambos resultados, asique pueden elegir el que ustedes prefieran

**Comment by amyaranta** [comment]
genial, muchas gracias :)

**Comment by CmPoblete** [comment]
En todo caso el output de ejemplo da el mismo resultado usando ints o floats.

**Comment by amyaranta** [comment]
siii, pero no sabia si en los tests que van a usar daba lo mismo
