### ISSUE TITLE
Error paso 3 instalación

### ISSUE THREAD

**Issue by tcouso** [IIC2143-2021-1/Syllabus#8]
## keyserver receive failed: No dirmngr

Hola!

Me está fallando la configuración en el primer comando del paso 3. Me preocupé de verificar que `dirmngr` estuviese instalado, pero aún así está fallando, así que cualquier ayuda se agradece mucho.

Saludos!

**Comment by matumartinez** [comment]
Hola!

¿Podrías enviar un pantallazo de tu terminal cuando da el error?

**Comment by tcouso** [comment]
Hola!

Finalmente creo que el problema fue que no podía actualizar a wsl 2. Arreglé eso usando la forma de instalación de windows insider y terminó funcionando súper. 

Gracias de todas formas por tu ayuda!
