### ISSUE TITLE
RVM is not a function

### ISSUE THREAD

**Issue by ElGarra** [IIC2143-2021-1/Syllabus#80]
Hola! tuve un problema con mi computador y tuve que formatear mi particion de linux. Al intentar instalar todo el setup tengo el siguiente problema al correr el comando rails new <nombre proyecto> --database=postgresql. Podrían ayudarme por favor?
![Captura de pantalla de 2021-04-12 18-09-28](https://user-images.githubusercontent.com/69603943/114469008-5e1b4580-9bba-11eb-8973-8a91ca6a579b.png)
![Captura de pantalla de 2021-04-12 18-09-31](https://user-images.githubusercontent.com/69603943/114469023-62476300-9bba-11eb-89c9-9e7e4658279a.png)

**Comment by jmndoza** [comment]
Hola! @ElGarra,
Puedes ver si esta instalado bundle con `bundle -v` ?
si no sale nada: `gem install bundle` 
si sale la version de bundle: `gem cleanup bundle`  y luego `gem install bundle`

**Comment by ElGarra** [comment]
Hola! @jerrymendoza  Muchas gracias por la ayuda, hice lo que me dijiste y al correr nuevamente elcomando me salió esto:

![Captura de pantalla de 2021-04-12 20-04-44](https://user-images.githubusercontent.com/69603943/114477573-62e7f580-9bca-11eb-904d-c09ff51eec29.png)
Alguna idea de que puede ser? Estoy siguiendo paso a paso los pasos

**Comment by meretamal** [comment]
Hola 😁 

Primero que todo, asegúrate de estar usando algún _release_ de **ruby 2.6**. Segundo, para instalar  `bundler`, ejecuta `gem install bundler`

**Comment by ElGarra** [comment]
Hola! @meretamal Intenté hacerlo de muchas formas pero cuando ejecuto el comando ruby -v me sigue apareciendo la version 2.5, tienes alguna idea de lo que podría ser_

**Comment by meretamal** [comment]
Estás usando rvm?

**Comment by ElGarra** [comment]
Si! estoy ejecuntando todo con rvm :(

**Comment by meretamal** [comment]
Ejecuta `rvm list` y mándame el _output_

**Comment by ElGarra** [comment]
![Uploading Captura de pantalla de 2021-04-12 20-45-38.png…]()

**Comment by ElGarra** [comment]
![Captura de pantalla de 2021-04-12 20-45-38](https://user-images.githubusercontent.com/69603943/114480212-228b7600-9bd0-11eb-9d1e-8e1cecf16387.png)

**Comment by meretamal** [comment]
Parece que no se están usando las versiones de ruby de rvm, sino que la del sistema. Si es que corres `rvm use 2.6.6 --default` y ejecutas `ruby -v` que te sale? (intenta también reiniciando el terminal)

**Comment by ElGarra** [comment]
![Captura de pantalla de 2021-04-12 20-49-36](https://user-images.githubusercontent.com/69603943/114480484-a2b1db80-9bd0-11eb-95e9-43ed0dafc078.png)

**Comment by meretamal** [comment]
Ejecuta:
```bash
source ~/.rvm/scripts/rvm
type rvm | head -n 1
```

y prueba de nuevo

Si es que funciona, reinicia tu terminal y ve si sigue funcionando, sino para mandarte otras cosas que tendrías que hacer

**Comment by ElGarra** [comment]
Seguí las instrucciones y me funcinó, pero al reiniciar el terminal volvió a salir la 2.5.
![Captura de pantalla de 2021-04-12 20-58-20](https://user-images.githubusercontent.com/69603943/114481140-fa9d1200-9bd1-11eb-8b39-9fb5c4cb2d19.png)
![Captura de pantalla de 2021-04-12 20-58-52](https://user-images.githubusercontent.com/69603943/114481176-0983c480-9bd2-11eb-9fa1-cee393db06e9.png)

**Comment by meretamal** [comment]
Perf, entonces, en ese mismo directorio donde estás corre `nano .bashrc` y agrega las dos líneas que te mandé antes. Luego presiona:
1. CTRL + X
2. y
3. ENTER

Reinicia tu terminal y todo debería funcionar

**Comment by ElGarra** [comment]
AHÍ ME FUNCIONÓ!!! MUCHISIMAS GRACIAS. Ahora debería intentar ejectuar el comando rails new nombre proyecto....? O debo ahcer algo antes?

**Comment by meretamal** [comment]
Es probable que tengas que instalar rails de nuevo

**Comment by ElGarra** [comment]
Ok, entonces vuelvo a hacer todo desde el paso 5?

**Comment by meretamal** [comment]
Si es que ya los habías hecho, en verdad sería repetir el 5 y luego desde el 8

**Comment by ElGarra** [comment]
![Captura de pantalla de 2021-04-12 21-16-39](https://user-images.githubusercontent.com/69603943/114482316-654f4d00-9bd4-11eb-88b0-e25656428098.png)
MUCHAS GRACIAAAAAAAAAS!!!!!!!!
