### ISSUE TITLE
Problema creando base de datos

### ISSUE THREAD

**Issue by stgopau** [IIC2143-2021-1/Syllabus#81]
Hola! tuve un problema con los dos últimos pasos del setup. Al crear la base de datos para la app. Al usar el comando rails db:create en mi computador (mac), no se crean las bases de datos arrojando lo siguiente: 
ActiveRecord::DatabaseConfigurations::InvalidConfigurationError: '{ default =>  }' is not a valid configuration. Expected '' to be a URL string or a Hash.
Luego al intentar correr el servidor me dice que ciertos archivos no se encontraron, me imagino que está relacionado con el problema anterior. Adjunto fotos de la consola.

rails db:create
![Captura de pantalla 2021-04-12 a la(s) 19 06 43](https://user-images.githubusercontent.com/53877157/114473596-8f980f00-9bc2-11eb-9612-d3880fbdcb56.png)
rails s
![Captura de pantalla 2021-04-12 a la(s) 19 08 36](https://user-images.githubusercontent.com/53877157/114473673-af2f3780-9bc2-11eb-8071-f15a6834515c.png)

**Comment by meretamal** [comment]
Hola 😁 , de la última foto se puede deducir que estás usando Rails 6. Primero que todo, asegúrate de estar creando tu proyecto con la versión 5.2.

**Comment by stgopau** [comment]
Sabes alguna forma de hacer esto? pOrque seguí la guía de setup y se debería haber instalado la versión 5.2.4, sin embargo esto no ocurrió y si intento ponerlo de nuevo se mantiene la versión más nueva que tengo yo. Intente desinstalando rails e instalándolo de nuevo con el comando del setup, "gem install rails -v 5.2.4", y aún así se mantiene en la versión más actualizada de rails que tengo yo (6.1.3.1).

**Comment by meretamal** [comment]
Intenta ejecutando `gem uninstall rails` y `gem uninstall railties`, y luego trata de instalar Rails 5.2.

Hay otras formas mejores de lograr esto, como usando [gemsets](https://rvm.io/gemsets/basics), por ejemplo.

**Comment by stgopau** [comment]
Ya habia intentado con el gem uninstall rails, y ahora con gem uninstall railties no pasa nada, me arroja lo siguiente.
![Captura de pantalla 2021-04-12 a la(s) 21 40 37](https://user-images.githubusercontent.com/53877157/114484276-e65c1380-9bd7-11eb-855e-2c4e193210c5.png)

**Comment by Melisa96** [comment]
Holaa, @stgopau pudiste resolverlo? me sale el mismo error :( pero tengo la versión 5.2.4 de rails
