### ISSUE TITLE
Nuevas columnas en modelos de rails

### ISSUE THREAD

**Issue by mc-cari** [IIC2143-2021-1/Syllabus#82]
Hola, siempre es bueno cambiar columnas de modelos mediante migraciones, o hay que borrar y crear otro modelo para evitar que se acumulen muchas migraciones?

**Comment by meretamal** [comment]
Hola 😁 

Ante cualquier cambio que quieras realizar sobre tu base de datos, lo que hagas puede depender de distintos factores:

1. Si es que la migración es nueva (la acabas de crear, por lo tanto, nadie más de tu equipo la tiene), te das cuenta que cometiste un error (te faltó un atributo, un nombre está mal, etc) y ya la ejecutaste. Para esto puedes correr `rails db:rollback` para deshacer la migración, realizar manualmente el cambio (editando el archivo de la migración) y luego ejecutar nuevamente `rails db:mimgrate`
2. Si es que la migración es vieja (y ya todos en tu equipo la tienen localmente y la ejecutaron), lo más recomendable es que crees una nueva migración para realizar algún cambio. Lo otro que puedes hacer es botar tu base de datos con `rails db:drop`, luego crearla de nuevo con `rails db:create` , luego editar la migración original y luego ejecutarlas. Esto último no es recomendable, ya que obligas a que todo tu equipo haga lo mismo, además de que, si no les avisas, su `app` seguirá corriendo y llegaran a encontrarse con un error, ya que no tienen ese cambio que hiciste.

**Comment by mc-cari** [comment]
Ya gracias
