### ISSUE TITLE
Cambiar de ubicación proyecto rails en WSL

### ISSUE THREAD

**Issue by OrregoSilva** [IIC2143-2021-1/Syllabus#83]
Hola!
Al crear un proyecto de rails, veo que este se ubica por defecto en ~ (asumo que es como el home de wsl), y quiero cambiarlo de ubicación a una carpeta que tengo en el escritorio, trate usando el comando `mv Proyecto '/mnt/c/Users/Martin Orrego/Desktop/Tests'` y al ejecutar `rails s` en la nueva ubicación no funciona, también trate crear uno usando `rails new  '/mnt/c/Users/Martin Orrego/Desktop/Tests/Proyecto' --database=postgresql` y no lo crea completo.
No se exactamente como es la manera correcta de hacer algo así o si simplemente no se puede (lo cual dudo).
Gracias por adelantado!

**Comment by meretamal** [comment]
Hola 😁 , me imagino que si `rails s` no te funcionó, es por problemas con el _path_. Te recomiendo que sigas trabajando desde ** ~**, para no tener estos errores.
