### ISSUE TITLE
ActiveRecord::NoDatabaseError

### ISSUE THREAD

**Issue by stgo32** [IIC2143-2021-1/Syllabus#84]
![nodatabaseerror](https://user-images.githubusercontent.com/69644287/114497541-63938280-9bf0-11eb-87dd-81911e667f70.jpg)

Hola, un compañero creó la app y le funcionó bien. Luego, nosotros la bajamos de github y no nos es posible correr la aplicación tirando el error de la foto. Me he conectado a pstgres y todavía me dice que la database no existe. También intentamos migrando la database y volver a hacer pull pero tampoco funcionó. Gracias!

**Comment by meretamal** [comment]
Hola 😁 

Todos ejecutaron `rails db:create`?

Esta base de datos corre localmente en sus propios computadores, por lo que todos deben crearla por su cuenta y hacer la configuración necesaria con variables de entorno.

**Comment by stgo32** [comment]
ahi funciono jajaj. gracias!
