### ISSUE TITLE
Conectar proyecto a git-Ruby on Rails

### ISSUE THREAD

**Issue by Emiliax16** [IIC2143-2021-1/Syllabus#85]
Hola! con mi grupo logramos conectar el proyecto a heroku, pero quisiéramos saber como podemos unirlo a la repo del grupo de git hub para subir los archivos del programa. 

Gracias!!

**Comment by matumartinez** [comment]
Hola!

Revisen la issue #75

**Comment by Emiliax16** [comment]
Hola! ya hicimos el deploy. Mi duda es si podemos conectar la app al repositorio de nuestro grupo, para poder trabajar en conjunto con mis compañeros.
