### ISSUE TITLE
  Error warning: shebang line ending with \r may cause problems al ejecutar rails server

### ISSUE THREAD

**Issue by Kevinnevik** [IIC2143-2021-1/Syllabus#86]
Hola tengo una duda al tratar de ejecutar el ejemplo que hicieron en la ultima ayudantía y cuando voy a ver localhost http://localhost:3000/  no me aparece nada

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/69523294/114629323-6640b700-9c86-11eb-954b-cde4a0f1ce0c.png">

**Comment by CmPoblete** [comment]
Hola, en el gemfile, en la primera línea que dice Ruby 2.6.3 (o algo asi), cambia ese número por 2.6.6
Aparentemente la ayudantía fue hecha con Ruby 2.6.3, pero ustedes tiene instalada la 2.6.6, entonces hay que hacer que rails sepa que se va a usar 2.6.6
