### ISSUE TITLE
Repositorios de equipo - Grupo creado pero no me aparece

### ISSUE THREAD

**Issue by MagnaThyrsus** [IIC2143-2021-1/Syllabus#87]
Holas
Me junte con mi grupo (Grupo 24) y aparentemente el repositorio fue creado, pero a mi no me aparece en la pagina principal. Ni siguiendo el url exacto lo puedo ver (Me aparece la pagina de 404 de github). Qué puedo hacer al respecto?

**Comment by meretamal** [comment]
Hola 😁 , parece que no aceptaste la invitación al _team_. Acabo de mandarte otra. Por favor acéptala lo antes posible, ya que vencen.

**Comment by icontreras2** [comment]
Hola @meretamal !! Me pasa exactamente lo mismo

**Comment by meretamal** [comment]
Hola @icontreras2 , cual es tu grupo? para poder reenviarte la invitación?

**Comment by icontreras2** [comment]
grupo 63 @meretamal !!
