### ISSUE TITLE
RSpec no retorna ningún output

### ISSUE THREAD

**Issue by rmena1** [IIC2143-2021-1/Syllabus#89]
Hola! Estoy tratando de implementar el testeo en nustro programa, pero al correr el comando "rails spec" en consola este no retorna nada. Al apretar enter al comando este se queda procesando por un segundo y luego me devuelve al input de la terminal, no entregando ningún output de error.
Instalé rspec tal como mencionan en la ayudantía 3 y logré implementar el testeo en el código de prueba de la ayudantía, pero ahora en mi app no logro hacer que funcione ni tampoco encuentro info útil en internet :(

**Comment by CmPoblete** [comment]
Hola, corriste el comando rails g rspec:install?

**Comment by rmena1** [comment]
Ya encontre el problema, había vuelto a una versión anterior de la app con git y en esta no estaba la gema en el gemfile, por eso no me reconocía el comando. Muchas gracias!
