### ISSUE TITLE
Error paso 4: Ensure you have installed shared-mime-info

### ISSUE THREAD

**Issue by valerianazal** [IIC2143-2021-1/Syllabus#9]
Hola! 
Tengo Mac y al correr el código `gem install rails -v 5.2.4` en el terminal  me tira el siguiente error:
<img width="770" alt="Screen Shot 2021-03-26 at 12 15 38" src="https://user-images.githubusercontent.com/69606605/112653236-faa8be00-8e2c-11eb-987b-7f9fdbdcc40a.png">
Intenté ejecutando nuevamente los códigos, pero no funcionó. Ojalá me puedan ayudar :)

Gracias!!

**Comment by alericoj10** [comment]
Hola !
Puedes probar instalando shared-mime-info, que el error dice no encontrarlo. Con: `brew install shared-mime-info`
También asegurate que tengas una version compatible con rails 5.2.4 de rubygems. Con: `gem update`

Quedo atento si te sirve.
Saludos!

**Comment by valerianazal** [comment]
Me funcionó! Muchas  gracias :)

**Comment by IgnaciaJ** [comment]
Hola! tengo un problema en el mismo paso pero con el comando rvm install 2.6, me tira el siguiente error la consola, que puedo hacer? gracias!
<img width="553" alt="Captura de Pantalla 2021-03-28 a la(s) 14 07 46" src="https://user-images.githubusercontent.com/69643709/112760905-092edb00-8fcf-11eb-8881-820ca678088b.png">

**Comment by alericoj10** [comment]
Hola!
Averiguando un poco encontré que puede tener relacion con una actualizacion de tu version de macOS en el pasado generando conflictos entre distintos package managers.
Si eso te hace sentido puedes probar eliminando el ejecutable `/opt/local/bin/libtool`
Y despues instalar de nuevo ruby con: `rvm install ruby-2.6 --with-openssl-dir='/opt/local'`

te dejo mi [referencia](https://github.com/rvm/rvm/issues/4484)
Cualquier cosa estoy atento!

**Comment by meretamal** [comment]
Hola @IgnaciaJ, por favor mira la issue #13. En el caso de que no te sirva, por favor abre otra _issue_, ya que el error en esta es distinto al tuyo

**Comment by IgnaciaJ** [comment]
Hola @alericoj10 @meretamal pude solucionar ese problema! muchas gracias!!
