### ISSUE TITLE
Version de Ruby del curso incompatible con Heroku

### ISSUE THREAD

**Issue by diegobustosk** [IIC2143-2021-1/Syllabus#90]
Hola, estaba probando hacer el deploy a heroku y por alguna razón no me esta dejando. Ya intente cambiar de la version 20 a la 18 y 16  y de igual manera no me deja hacer el deploy.
Me aparece el siguiente error

#
![Captura de Pantalla 2021-04-13 a la(s) 15 40 05](https://user-images.githubusercontent.com/45362040/114736933-89b24300-9d14-11eb-8147-4c330556515c.png)
![Captura de Pantalla 2021-04-13 a la(s) 15 40 18](https://user-images.githubusercontent.com/45362040/114736949-8e76f700-9d14-11eb-811f-56af02ef71ce.png)

**Comment by matumartinez** [comment]
Hola!

Prueba cambiando la versión de rails a 5.2.4 y bundle update.

**Comment by diegobustosk** [comment]
Perfecto ahora si pude descargar la 5.2.4. Tenia q descargar  mimedata . Gracias
