### ISSUE TITLE
Error con Heroku CLI: error: cannot communicate with server: Post http://localhost/v2/snaps/heroku: dial unix /run/snapd.socket: connect: no such file or directory

### ISSUE THREAD

**Issue by jaliaga0899** [IIC2143-2021-1/Syllabus#91]
Hola!
Al momento de instalar Heroku CLI en Ubuntu, me salio el siguiente error

error: cannot communicate with server: Post http://localhost/v2/snaps/heroku: dial unix /run/snapd.socket: connect: no such file or directory

No he podido pillar que lo produce, pero pasa al momento de instalar Heroku CLI segun el tutorial de la página

sudo snap install --classic heroku

**Comment by matumartinez** [comment]
Hola!

Prueba con lo siguiente:

`
sudo systemctl unmask snapd.service
`
`
sudo systemctl enable snapd.service
`
`
sudo systemctl start snapd.service
`

Después prueba instalar Heroku, quedo atento a si te funciona.

**Comment by jaliaga0899** [comment]
![ubuntu_kJGChdpMn6](https://user-images.githubusercontent.com/48482638/114769336-15899680-9d38-11eb-94ae-e90748115800.png)
Adjunto imagen de problema que sale luego de intentar con lo mencionado (luego, al instalar heroku, nuevamente hay error)

**Comment by matumartinez** [comment]
Qué error te da ahora con heroku? El mismo de antes?

**Comment by jaliaga0899** [comment]
Si, el mismo que antes
![ubuntu_JvaoJIFHjn](https://user-images.githubusercontent.com/48482638/114784334-170f8a80-9d49-11eb-90f3-25f475db2d2a.png)

**Comment by matumartinez** [comment]
Prueba con esto:

sudo service snapd.service unmask
sudo service snapd.service enable
sudo service snapd.service start

**Comment by jaliaga0899** [comment]
![ubuntu_qh7jLdGxr4](https://user-images.githubusercontent.com/48482638/114794460-88a40480-9d5a-11eb-8eb1-8657669c2cd4.png)
Unrecognized service me aparece
