### ISSUE TITLE
Duda branches al clonar el repo del grupo

### ISSUE THREAD

**Issue by jaliaga0899** [IIC2143-2021-1/Syllabus#92]
Hola!

Cuando cloné el repositorio privado del grupo a mi computador, pude notar que no se clonó la rama branch.
Creé la rama branch desde mi computador (por que no habia notado que existía en el remote) y al tratar de actualizarla y pushearla para que los demás integrantes del proyecto puedan pullear las branches, no se genera un push desde mi computador.

Queria saber si es que estaba haciendo bien el tema del push

Tengo entendido que tengo que hacer, desde la rama master
git add .
git commit -m "mensaje"
git push

o si hay otra razón por la que no se actualiza el repositorio (o no se haya clonado con la rama develop desde remote)

**Comment by matumartinez** [comment]
Hola!

Si es que quieres modificar la rama "branch", localmente debes hacer push posicionándote en esa rama, no desde la rama master.

**Comment by jaliaga0899** [comment]
Y es común que se haya clonado el repo sin la branch develop incluida?

**Comment by matumartinez** [comment]
Después de clonar el repo tienes que crear las otras ramas localmente (con el mismo nombre) y hacer git pull.

**Comment by Baelfire18** [comment]
@jaliaga0899 Acá tienes un par de comandos de gitflow:
```
Crear: git checkout -b <name>
Borrar: git checkout -d <name>
Push: git push origin <name>
Cambiar: git checkout <name>
Merge: (Te ubicas en la receptor antes y la fusionas con la de nombre name) git merge <name>
```

Puedes averiguar más cosas en esta [guía](https://rogerdudler.github.io/git-guide/).

**Comment by jaliaga0899** [comment]
muchas gracias! se pasaron

**Comment by matumartinez** [comment]
También hay git cheat sheets como este: https://www.git-tower.com/blog/git-cheat-sheet
