### ISSUE TITLE
Eliminar repositorio clonado

### ISSUE THREAD

**Issue by Gustav2000** [IIC2143-2021-1/Syllabus#94]
Hola, tengo un problema ya que cloné un repositorio y luego intenté eliminarlo (sobre la carpeta, botón derecho > eliminar), pero resulta que no se elimina. Ya está sin ningún archivo adentro pero queda la carpeta oculta .git. Ya había hecho esto mismo con otros repositorios que a veces los eliminaba y luego los volvía a clonar, pero por alguna razón ahora no me deja. Que soluciones pueden haber. 

De todas formas ahora le cambie el nombre y pude clonar de nuevo el repositorio, sin embargo me interesa poder borrar el anterior.

Muchas gracias de antemano.

**Comment by meretamal** [comment]
Hola 😁 

Desde tu terminal puedes intentar correr `rm -rf path_a_tu_carpeta`

**Comment by Gustav2000** [comment]
Es que traté con ese comando pero esto es lo que me aparece.
![image](https://user-images.githubusercontent.com/62355739/115088911-2a545e80-9edf-11eb-9ffc-5fa0a8d11986.png)
No se si me puedas ayudar 🤔

**Comment by terraloyd2009-cyber** [comment]
Hola.😄

Lo que pasa es que no tienes los permisos necesarios para eliminarlo. Utiliza `sudo rm -rf nombre_carpeta/archivo`.

Se que ya pasaron muchos años pero eso es lo que puedo dar por si a alguien más le pasa lo mismo.
