### ISSUE TITLE
Duda características generales entrega 1

### ISSUE THREAD

**Issue by festelle** [IIC2143-2021-1/Syllabus#95]
El enunciado dice que el usuario primero se debe registrar para poder ver las publicaciones, pero no entendemos mucho este punto, porque pensamos que tiene más sentido que cualquier persona pueda ver las publicaciones hechas antes de registrarse.
Entonces, es obligación que se tenga que iniciar sesión para ver las publicaciones?

**Comment by Baelfire18** [comment]
A mi vista tiene sentido lo que dices. Un usuario visita pueda ver las publicaciones; un usuario registrado pueda crearlas, comentarlas, etc; y un usuario administrador pueda por ejemplo borrarlas. Eso al menos para mis grupos.
Pero conversalo directamente con tu Product Owner, de él dependen los requisitos que tendría tu página.

**Comment by meretamal** [comment]
Hola 😁 

Tal como dice @Baelfire18, háblalo con tu _producto owner_, ya que él es quien define las funcionalidades y el funcionamiento del proyecto
