### ISSUE TITLE
 warning: shebang line ending with \r may cause problems

### ISSUE THREAD

**Issue by Fernan-tess** [IIC2143-2021-1/Syllabus#96]
Hola,
Hice pull a la app de mi compañero de grupo, que sí está funcionando, pero al momento de ejecutar rails db:create, me aparece ese warning, y no crea la base de datos.

Modifiqué el archivo .ENV y estoy conectado a psql, pero no sé por qué no me corre.

**Comment by Fernan-tess** [comment]
![image](https://user-images.githubusercontent.com/53883016/114951900-42ff3e80-9e23-11eb-92f4-b5c556af9ad6.png)

**Comment by CmPoblete** [comment]
Hola, prueba instalando node

**Comment by Baelfire18** [comment]
Prueba usando estos 2 comandos en consola:
```
git config --global core.autocrlf true
rails app:update:bin
```
