### ISSUE TITLE
Problemas al descargar Heroku CLI en windows

### ISSUE THREAD

**Issue by ignaciovilla** [IIC2143-2021-1/Syllabus#98]
Al tratar de instalar heroku CLI me aparece el siguiente aviso:
"This app has been blocked for your protection"
"An administrator has blocked you from running this app. For more infromation contact the administrator."

Quería saber si es que alguien sabe como solucionarlo de manera seguro, o si es que hay alguna otra forma de hacer el deploy de la aplicación.
Muchas gracias

**Comment by meretamal** [comment]
Hola 😁 

Estás instalándolo en Windows o WSL (ubuntu)?

**Comment by ignaciovilla** [comment]
En Windows, te dejo una foto del problema 
![WhatsApp Image 2021-04-16 at 17 53 20](https://user-images.githubusercontent.com/62113032/115087761-cd57a900-9edc-11eb-89a5-ea7f5621c04f.jpeg)
