### ISSUE TITLE
Error al ejecutar comando: psql postgres (Mac)

### ISSUE THREAD

**Issue by juanluis2019** [IIC2143-2021-1/Syllabus#99]
El ejecutar: psql postgres, me sale el siguiente error

psql: error: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by meretamal** [comment]
Hola, por favor inicia un servicio postgres primero. Sale en la guía de _setup_ cómo hacerlo, dependiendo de tu sistema operativo
